"use strict";
const assert = require("node:assert/strict"); const fs = require("node:fs"); const os = require("node:os"); const path = require("node:path"); const test = require("node:test"); const { persistAniccaDaily, persistHonneDaily, persistWeeklyReview } = require("./marketing-product-summary.js");

test("Honne daily summary binds EN and JA immutable daily sources and replays", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-honne-summary-")); const day = "2026-08-22";
  for (const target of [{ owner: "honne_reveal", account: "@honne_reveal", locale: "en", video: "1", views: 208 }, { owner: "honnevideo", account: "@honnevideo", locale: "ja", video: "2", views: 1035 }]) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics", target.owner, target.video, "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ kind: "tiktok_daily_metric_digest", window: "daily", observed_at: `2026-08-22T${target.locale === "en" ? "10" : "11"}:00:00.000Z`, account_id: target.account, locale: target.locale, public_url: `https://www.tiktok.com/${target.account}/video/${target.video}`, post: { views: { status: "measured", value: target.views }, likes: { status: "measured", value: 1 }, comments: { status: "measured", value: 0 }, shares: { status: "measured", value: 0 }, saves: { status: "unavailable" }, engagement: { status: "derived", percent: 1 } }, account_metrics: { followers: { status: "measured", value: 5 }, following: { status: "measured", value: 1 }, total_likes: { status: "measured", value: 10 }, videos: { status: "measured", value: 2 } } })); }
  const first = persistHonneDaily(dataDir, day, "2026-08-22T13:00:00.000Z"); const replay = persistHonneDaily(dataDir, day, "2026-08-22T14:00:00.000Z"); assert.equal(first.created, true); assert.equal(replay.created, false); assert.equal(first.snapshot.source_refs.length, 2); assert.match(first.snapshot.message, /@honne_reveal TikTok: Views 208/); assert.match(first.snapshot.message, /@honnevideo TikTok: Views 1035/); assert.match(first.snapshot.message, /Installs: 取得不可/); assert.equal(fs.statSync(first.file).mode & 0o777, 0o600);
});

test("Anicca daily summary binds main sources and keeps JP4 and HE unavailable", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-anicca-summary-")); const day = "2026-08-22"; const rows = [{ owner: "anicca.jp", account: "@anicca.jp", platform: "tiktok", url: "https://www.tiktok.com/@anicca.jp/video/1" }, { owner: "anicca.ios.jp", account: "@anicca.jp1", platform: "instagram", url: "https://www.instagram.com/reel/ABC123/" }];
  for (const [index, target] of rows.entries()) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics", target.owner, String(index + 1), "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ kind: `${target.platform}_daily_metric_digest`, window: "daily", observed_at: `2026-08-22T1${index}:00:00.000Z`, account_id: target.account, locale: "ja", public_url: target.url, post: { views: { status: "measured", value: 100 + index }, likes: { status: "measured", value: 1 }, comments: { status: "measured", value: 0 }, shares: { status: "measured", value: 0 }, saves: { status: "unavailable" }, engagement: { status: "derived", percent: 1 } }, account_metrics: { status: "unavailable" } })); }
  const result = persistAniccaDaily(dataDir, day, "2026-08-22T13:00:00.000Z"); assert.equal(result.created, true); assert.equal(result.snapshot.source_refs.length, 2); assert.match(result.snapshot.message, /@anicca\.jp TikTok: Views 100/); assert.match(result.snapshot.message, /@anicca\.jp1 Instagram: Views 101/); assert.match(result.snapshot.message, /@anicca\.jp4 TikTok: 全social\/account metrics取得不可/); assert.match(result.snapshot.message, /@anicca\.he TikTok: 全social\/account metrics取得不可/); assert.match(result.snapshot.message, /7676500512308481296/);
});

test("weekly review binds both products without cross-product winner transfer", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-weekly-summary-")); const day = "2026-08-22";
  for (const [product, label] of [["honne-ai", "Honne AI"], ["anicca-ios", "Anicca iOS"]]) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics/summaries", product, "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", period: "daily", report_key: day, observed_at: "2026-08-22T13:00:00.000Z", product_id: product, source_refs: [], message: `Life Manager::: ${label} source values` })); }
  const first = persistWeeklyReview(dataDir, day, "2026-08-22T14:00:00.000Z"); const replay = persistWeeklyReview(dataDir, day, "2026-08-22T15:00:00.000Z"); assert.equal(first.created, true); assert.equal(replay.created, false); assert.equal(first.snapshot.period, "weekly"); assert.equal(first.snapshot.report_key, "2026-W34"); assert.equal(first.snapshot.source_refs.length, 2); assert.match(first.snapshot.message, /Honne AI source values/); assert.match(first.snapshot.message, /Anicca iOS source values/); assert.match(first.snapshot.message, /Cross-product winner: 判定しない/); assert.match(first.snapshot.message, /Attribution coverage: 取得不可/); assert.equal(fs.statSync(first.file).mode & 0o777, 0o600);
});
