"use strict";
const assert = require("node:assert/strict"); const fs = require("node:fs"); const os = require("node:os"); const path = require("node:path"); const test = require("node:test"); const { importContentObject } = require("../lib/content-object-store.js"); const { persistAniccaDaily, persistAttributionCoverage, persistHonneDaily, persistWeeklyReview } = require("./marketing-product-summary.js");

test("attribution coverage joins product totals while keeping activation and retention unavailable", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-attribution-summary-")); const day = "2026-08-23"; const objectDir = path.join(dataDir, "objects");
  const source = path.join(dataDir, "source.json"); fs.writeFileSync(source, "{}\n"); const ref = importContentObject(source, { objectDir }).ref;
  const ascDir = path.join(dataDir, "tenants/dais-local/marketing/attribution/asc", day); fs.mkdirSync(ascDir, { recursive: true });
  fs.writeFileSync(path.join(ascDir, "acquisition.json"), JSON.stringify({ snapshot_ref: ref, products: [{ product_id: "anicca-ios", source_status: "measured", metrics: { first_time_downloads: { status: "measured", value: 1 } } }, { product_id: "honne-ai", source_status: "unavailable", metrics: { first_time_downloads: { status: "unavailable", value: null, reason: "report_pending" } } }], rows: [{ product_id: "anicca-ios", account_id: "@anicca.jp", platform: "tiktok", provider_post_id: "post-a", public_url: "https://www.tiktok.com/@anicca.jp/video/1", acquisition_status: "unattributed", acquisition_reason: "campaign_not_configured", product_observation_status: "measured" }, { product_id: "honne-ai", account_id: "@honne_reveal", platform: "tiktok", provider_post_id: "post-b", public_url: "https://www.tiktok.com/@honne_reveal/video/2", acquisition_status: "unattributed", acquisition_reason: "campaign_not_configured", product_observation_status: "unavailable" }] }));
  const rcDir = path.join(dataDir, "tenants/dais-local/marketing/attribution/revenuecat", day); fs.mkdirSync(rcDir, { recursive: true });
  fs.writeFileSync(path.join(rcDir, "subscriptions.json"), JSON.stringify({ snapshot_ref: ref, products: ["anicca-ios", "honne-ai"].map((product_id) => ({ product_id, source_status: "unavailable", metrics: { trial_starts: { status: "unavailable", value: null, reason: "missing" }, active_subscriptions: { status: "unavailable", value: null, reason: "missing" }, renewals: { status: "unavailable", value: null, reason: "missing" }, cancellations: { status: "unavailable", value: null, reason: "missing" }, proceeds_usd: { status: "unavailable", value: null, reason: "missing" } } })) }));
  const first = persistAttributionCoverage(dataDir, day, "2026-08-23T13:00:00.000Z"); const replay = persistAttributionCoverage(dataDir, day, "2026-08-23T14:00:00.000Z");
  assert.equal(first.created, true); assert.equal(replay.created, false); assert.equal(first.snapshot.source_refs.length, 2);
  assert.match(first.snapshot.message, /Anicca iOS: Install 1/); assert.match(first.snapshot.message, /Activation 取得不可/); assert.match(first.snapshot.message, /D1 retention 取得不可/); assert.match(first.snapshot.message, /Honne AI: Install 取得不可/); assert.match(first.snapshot.message, /campaign attribution: 取得不可/);
  assert.equal(first.snapshot.products[0].metrics.activation.value, null); assert.equal(first.snapshot.products[0].metrics.d7_retention.value, null);
  assert.equal(first.snapshot.effects.length, 2);
  assert.deepEqual(first.snapshot.effects.map(({ account_id, attribution_status }) => ({ account_id, attribution_status })), [{ account_id: "@anicca.jp", attribution_status: "unattributed" }, { account_id: "@honne_reveal", attribution_status: "unattributed" }]);
  assert.deepEqual(first.snapshot.account_coverage.map(({ product_id, account_id, effect_count }) => ({ product_id, account_id, effect_count })), [{ product_id: "anicca-ios", account_id: "@anicca.jp", effect_count: 1 }, { product_id: "honne-ai", account_id: "@honne_reveal", effect_count: 1 }]);
});

test("attribution coverage upgrades a legacy summary through an immutable correction", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-attribution-correction-")); const day = "2026-08-23"; const objectDir = path.join(dataDir, "objects");
  const source = path.join(dataDir, "source.json"); fs.writeFileSync(source, "{}\n"); const ref = importContentObject(source, { objectDir }).ref;
  const ascDir = path.join(dataDir, "tenants/dais-local/marketing/attribution/asc", day); fs.mkdirSync(ascDir, { recursive: true });
  const product = (product_id) => ({ product_id, source_status: "measured", metrics: { first_time_downloads: { status: "measured", value: 1 } } });
  fs.writeFileSync(path.join(ascDir, "acquisition.json"), JSON.stringify({ snapshot_ref: ref, products: [product("anicca-ios"), product("honne-ai")], rows: [{ product_id: "anicca-ios", account_id: "@anicca.jp", platform: "tiktok", provider_post_id: "post-a", public_url: "https://www.tiktok.com/@anicca.jp/video/1", acquisition_status: "unattributed", acquisition_reason: "campaign_not_configured", product_observation_status: "measured" }] }));
  const rcDir = path.join(dataDir, "tenants/dais-local/marketing/attribution/revenuecat", day); fs.mkdirSync(rcDir, { recursive: true });
  const metrics = { trial_starts: { status: "unavailable", value: null, reason: "missing" }, active_subscriptions: { status: "unavailable", value: null, reason: "missing" }, renewals: { status: "unavailable", value: null, reason: "missing" }, cancellations: { status: "unavailable", value: null, reason: "missing" }, proceeds_usd: { status: "unavailable", value: null, reason: "missing" } };
  fs.writeFileSync(path.join(rcDir, "subscriptions.json"), JSON.stringify({ snapshot_ref: ref, products: ["anicca-ios", "honne-ai"].map((product_id) => ({ product_id, source_status: "unavailable", metrics })) }));
  const coverageDir = path.join(dataDir, "tenants/dais-local/marketing/attribution/coverage", day); fs.mkdirSync(coverageDir, { recursive: true });
  fs.writeFileSync(path.join(coverageDir, "summary.json"), JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", report_key: `attribution-${day}`, products: [] }));
  const upgraded = persistAttributionCoverage(dataDir, day, "2026-08-23T13:00:00.000Z"); const replay = persistAttributionCoverage(dataDir, day, "2026-08-23T14:00:00.000Z");
  assert.equal(upgraded.created, true); assert.match(upgraded.file, /summary\.correction\.json$/); assert.equal(upgraded.snapshot.effects.length, 1); assert.equal(replay.created, false); assert.equal(replay.snapshot_ref, upgraded.snapshot_ref);
});

test("Honne daily summary binds EN and JA immutable daily sources and replays", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-honne-summary-")); const day = "2026-08-22";
  for (const target of [{ owner: "honne_reveal", account: "@honne_reveal", locale: "en", video: "1", views: 208 }, { owner: "honnevideo", account: "@honnevideo", locale: "ja", video: "2", views: 1035 }]) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics", target.owner, target.video, "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ kind: "tiktok_daily_metric_digest", window: "daily", observed_at: `2026-08-22T${target.locale === "en" ? "10" : "11"}:00:00.000Z`, account_id: target.account, locale: target.locale, public_url: `https://www.tiktok.com/${target.account}/video/${target.video}`, post: { views: { status: "measured", value: target.views }, likes: { status: "measured", value: 1 }, comments: { status: "measured", value: 0 }, shares: { status: "measured", value: 0 }, saves: { status: "unavailable" }, engagement: { status: "derived", percent: 1 } }, account_metrics: { followers: { status: "measured", value: 5 }, following: { status: "measured", value: 1 }, total_likes: { status: "measured", value: 10 }, videos: { status: "measured", value: 2 } } })); }
  const first = persistHonneDaily(dataDir, day, "2026-08-22T13:00:00.000Z"); const replay = persistHonneDaily(dataDir, day, "2026-08-22T14:00:00.000Z"); assert.equal(first.created, true); assert.equal(replay.created, false); assert.equal(first.snapshot.source_refs.length, 2); assert.match(first.snapshot.message, /@honne_reveal TikTok: Views 208/); assert.match(first.snapshot.message, /@honnevideo TikTok: Views 1035/); assert.match(first.snapshot.message, /Funnel: Install 取得不可、Activation 取得不可/); assert.equal(fs.statSync(first.file).mode & 0o777, 0o600);
});

test("Anicca daily summary binds main sources and keeps JP4 and HE unavailable", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-anicca-summary-")); const day = "2026-08-22"; const rows = [{ owner: "anicca.jp", account: "@anicca.jp", platform: "tiktok", url: "https://www.tiktok.com/@anicca.jp/video/1" }, { owner: "anicca.ios.jp", account: "@anicca.jp1", platform: "instagram", url: "https://www.instagram.com/reel/ABC123/" }];
  for (const [index, target] of rows.entries()) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics", target.owner, String(index + 1), "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ kind: `${target.platform}_daily_metric_digest`, window: "daily", observed_at: `2026-08-22T1${index}:00:00.000Z`, account_id: target.account, locale: "ja", public_url: target.url, post: { views: { status: "measured", value: 100 + index }, likes: { status: "measured", value: 1 }, comments: { status: "measured", value: 0 }, shares: { status: "measured", value: 0 }, saves: { status: "unavailable" }, engagement: { status: "derived", percent: 1 } }, account_metrics: { status: "unavailable" } })); }
  const result = persistAniccaDaily(dataDir, day, "2026-08-22T13:00:00.000Z"); assert.equal(result.created, true); assert.equal(result.snapshot.source_refs.length, 2); assert.match(result.snapshot.message, /@anicca\.jp TikTok: Views 100/); assert.match(result.snapshot.message, /@anicca\.jp1 Instagram: Views 101/); assert.match(result.snapshot.message, /@anicca\.jp4 TikTok: 全social\/account metrics取得不可/); assert.match(result.snapshot.message, /@anicca\.he TikTok: 全social\/account metrics取得不可/); assert.match(result.snapshot.message, /7676500512308481296/);
});

test("Anicca daily summary covers every selected account and joins cadence health", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-anicca-full-summary-")); const day = "2026-08-28"; const core = [["anicca.jp", "@anicca.jp", "tiktok", "https://www.tiktok.com/@anicca.jp/video/1001"], ["anicca.ios.jp", "@anicca.jp1", "instagram", "https://www.instagram.com/reel/CORE2/"]];
  const extras = [
    ["ani.cca1234", "@ani.cca1234", "instagram", "https://www.instagram.com/p/CAROUSEL1/"],
    ["anicca.jp.videos", "@anicca.jp.videos", "instagram", "https://www.instagram.com/reel/WIDGETJA1/"],
    ["anicca.encards", "@anicca.encards", "instagram", "https://www.instagram.com/reel/CARDEN1/"],
    ["anicca.en", "@anicca.en", "instagram", "https://www.instagram.com/reel/WIDGETEN1/"],
    ["anicca.affirmation", "@anicca.affirmation", "instagram", "https://www.instagram.com/p/AFFIRM1/"],
    ["anicca_slideshow", "@anicca_slideshow", "tiktok", "unavailable"],
    ["obou.anicca", "@obou.anicca", "instagram", "https://www.instagram.com/reel/OBOU1/"],
  ];
  for (const [owner, account, platform, public_url] of core.concat(extras)) {
    const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics", owner, "effect", "daily"); fs.mkdirSync(directory, { recursive: true });
    const locale = ["@anicca.encards", "@anicca.en", "@anicca.affirmation", "@anicca_slideshow"].includes(account) ? "en" : "ja";
    fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ kind: `${platform}_daily_metric_digest`, window: "daily", observed_at: "2026-08-28T12:00:00.000Z", account_id: account, locale, public_url, post: { views: { status: "measured", value: 1 }, likes: { status: "measured", value: 0 }, comments: { status: "measured", value: 0 }, shares: { status: "measured", value: 0 }, saves: { status: "measured", value: 0 }, engagement: { status: "measured", percent: 0 } }, account_metrics: { status: "unavailable" } }));
  }
  const cadence = path.join(dataDir, "marketing/cadence", `${day}.json`); fs.mkdirSync(path.dirname(cadence), { recursive: true }); fs.writeFileSync(cadence, JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", product_id: "mobile-marketing", report_day: day, counts: { published: 13, pending: 2, missed: 24, duplicate: 0 }, routes: [] }));
  const result = persistAniccaDaily(dataDir, day, "2026-08-28T13:00:00.000Z");
  assert.equal(result.snapshot.account_coverage.length, 11);
  assert.equal(result.snapshot.account_coverage.find(({ account_id }) => account_id === "@anicca_slideshow").status, "measured");
  assert.match(result.snapshot.message, /Cadence: Published 13、Pending 2、Missed 24、Duplicate 0/);
});

test("weekly review binds both products without cross-product winner transfer", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-weekly-summary-")); const day = "2026-08-22";
  for (const [product, label] of [["honne-ai", "Honne AI"], ["anicca-ios", "Anicca iOS"]]) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics/summaries", product, "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", period: "daily", report_key: day, observed_at: "2026-08-22T13:00:00.000Z", product_id: product, source_refs: [], message: `Life Manager::: ${label} source values` })); }
  const first = persistWeeklyReview(dataDir, day, "2026-08-22T14:00:00.000Z"); const replay = persistWeeklyReview(dataDir, day, "2026-08-22T15:00:00.000Z"); assert.equal(first.created, true); assert.equal(replay.created, false); assert.equal(first.snapshot.period, "weekly"); assert.equal(first.snapshot.report_key, "2026-W34"); assert.equal(first.snapshot.source_refs.length, 2); assert.match(first.snapshot.message, /Honne AI source values/); assert.match(first.snapshot.message, /Anicca iOS source values/); assert.match(first.snapshot.message, /Cross-product winner: 判定しない/); assert.match(first.snapshot.message, /Attribution coverage: 取得不可/); assert.equal(fs.statSync(first.file).mode & 0o777, 0o600);
});

test("weekly review prefers daily corrections and includes cadence plus hook state", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-weekly-full-review-")); const day = "2026-08-28"; const objectDir = path.join(dataDir, "objects");
  for (const product of ["honne-ai", "anicca-ios"]) {
    const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics/summaries", product, "daily"); fs.mkdirSync(directory, { recursive: true });
    fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", period: "daily", report_key: day, observed_at: "2026-08-28T12:00:00.000Z", product_id: product, source_refs: [], message: `${product} stale daily` }));
    fs.writeFileSync(path.join(directory, `${day}.correction.json`), JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", period: "daily", report_key: day, observed_at: "2026-08-28T13:00:00.000Z", product_id: product, source_refs: [], message: `${product} corrected daily` }));
  }
  const cadence = path.join(dataDir, "marketing/cadence", `${day}.json`); fs.mkdirSync(path.dirname(cadence), { recursive: true }); fs.writeFileSync(cadence, JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", product_id: "mobile-marketing", report_day: day, counts: { published: 13, pending: 2, missed: 24, duplicate: 0 }, routes: [] }));
  const experiments = path.join(dataDir, "tenants/dais-local/marketing/experiments"); fs.mkdirSync(experiments, { recursive: true });
  for (const [name, kind, payload] of [["hook-decisions", "marketing_hook_decisions", { decisions: [{ lane_id: "honne-en", decision_status: "pending", decision: null, reason: "attribution_unavailable" }] }], ["hook-consumption-proofs", "marketing_hook_consumption_proofs", { proofs: [{ assignment_id: "a", status: "pending", reason: "decision_pending" }] }]]) {
    const source = path.join(dataDir, `${name}-source.json`); fs.writeFileSync(source, JSON.stringify({ schema_version: 1, kind, tenant_id: "dais-local", ...payload })); const ref = importContentObject(source, { objectDir }).ref; fs.writeFileSync(path.join(experiments, `${name}.json`), JSON.stringify({ schema_version: 1, kind, tenant_id: "dais-local", snapshot_ref: ref, ...payload }));
  }
  const result = persistWeeklyReview(dataDir, day, "2026-08-28T14:00:00.000Z");
  assert.match(result.snapshot.message, /honne-ai corrected daily/); assert.match(result.snapshot.message, /Cadence.*Published 13/); assert.match(result.snapshot.message, /Hook decisions:.*pending/); assert.match(result.snapshot.message, /Hook consumption:.*pending/); assert.ok(result.snapshot.source_refs.some((ref) => ref === importContentObject(cadence, { objectDir }).ref)); assert.equal(result.snapshot.cadence.length, 7); assert.equal(result.snapshot.hook_decisions.items[0].decision_status, "pending"); assert.ok(result.snapshot.message.length <= 4096);
});

test("weekly review writes a new immutable correction when the prior one exceeds Telegram size", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-weekly-correction-revision-")); const day = "2026-08-28"; const objectDir = path.join(dataDir, "objects");
  for (const product of ["honne-ai", "anicca-ios"]) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics/summaries", product, "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", period: "daily", report_key: day, observed_at: "2026-08-28T12:00:00.000Z", product_id: product, source_refs: [], message: `${product} daily` })); }
  const cadence = path.join(dataDir, "marketing/cadence", `${day}.json`); fs.mkdirSync(path.dirname(cadence), { recursive: true }); fs.writeFileSync(cadence, JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", product_id: "mobile-marketing", report_day: day, counts: { published: 1, pending: 0, missed: 0, duplicate: 0 }, routes: [] }));
  const experiments = path.join(dataDir, "tenants/dais-local/marketing/experiments"); fs.mkdirSync(experiments, { recursive: true }); for (const [name, kind, key] of [["hook-decisions", "marketing_hook_decisions", "decisions"], ["hook-consumption-proofs", "marketing_hook_consumption_proofs", "proofs"]]) { const source = path.join(dataDir, `${name}-source.json`); fs.writeFileSync(source, JSON.stringify({ schema_version: 1, kind, tenant_id: "dais-local", [key]: [] })); const ref = importContentObject(source, { objectDir }).ref; fs.writeFileSync(path.join(experiments, `${name}.json`), JSON.stringify({ schema_version: 1, kind, tenant_id: "dais-local", snapshot_ref: ref, [key]: [] })); }
  const weeklyDir = path.join(dataDir, "tenants/dais-local/marketing/metrics/summaries/mobile-marketing/weekly"); fs.mkdirSync(weeklyDir, { recursive: true }); fs.writeFileSync(path.join(weeklyDir, "2026-W35.correction.json"), JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", cadence: [], hook_decisions: {}, hook_consumption: {}, message: "x".repeat(5000) }));
  const result = persistWeeklyReview(dataDir, day, "2026-08-28T14:00:00.000Z"); assert.equal(result.created, true); assert.match(result.file, /2026-W35\.correction\.2\.json$/); assert.ok(result.snapshot.message.length <= 4096);
});
