#!/usr/bin/env bash
set -euo pipefail
if [[ $# -ne 2 || ! -f "$1" || ! -f "$2" ]]; then echo "usage: verify-funder-gates-railway <day-gate.json> <freshness-gate.json>" >&2; exit 2; fi
DAY_GATE="$1"; FRESH_GATE="$2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
node -e 'const fs=require("node:fs"),{validateFunderSubmissionDayGate}=require(process.argv[1]);validateFunderSubmissionDayGate(JSON.parse(fs.readFileSync(process.argv[2],"utf8")))' "$SCRIPT_DIR/../lib/funder-submission-day.js" "$DAY_GATE"
node "$SCRIPT_DIR/verify-funder-freshness-gate.js" "$FRESH_GATE" >/dev/null
jq -e '(.tenant_id|test("^[A-Za-z0-9._-]{1,128}$")) and (.attempt_id|test("^[0-9a-f-]{36}$";"i")) and (.gate_id|test("^funder-day-gate:[0-9a-f]{64}$")) and (.gate_digest|test("^[0-9a-f]{64}$")) and .submit_allowed==true and .decision=="allow"' "$DAY_GATE" >/dev/null
jq -e '(.tenant_id|test("^[A-Za-z0-9._-]{1,128}$")) and (.attempt_id|test("^[0-9a-f-]{36}$";"i")) and (.gate_id|test("^funder-freshness-gate:[0-9a-f]{64}$")) and (.gate_digest|test("^[0-9a-f]{64}$")) and .submit_allowed==true and .decision=="allow"' "$FRESH_GATE" >/dev/null
TENANT=$(jq -r '.tenant_id' "$DAY_GATE"); ATTEMPT=$(jq -r '.attempt_id' "$DAY_GATE"); DAY_ID=$(jq -r '.gate_id' "$DAY_GATE"); DAY_DIGEST=$(jq -r '.gate_digest' "$DAY_GATE"); DAY_SIGNATURE=$(jq -r '.attestation_signature' "$DAY_GATE"); FUNDER=$(jq -r '.funder_id' "$DAY_GATE"); TOKYO_DAY=$(jq -r '.tokyo_day' "$DAY_GATE"); DAY_EVALUATED=$(jq -r '.evaluated_at' "$DAY_GATE"); FRESH_ID=$(jq -r '.gate_id' "$FRESH_GATE"); FRESH_DIGEST=$(jq -r '.gate_digest' "$FRESH_GATE")
[[ "$TENANT" == "$(jq -r '.tenant_id' "$FRESH_GATE")" && "$ATTEMPT" == "$(jq -r '.attempt_id' "$FRESH_GATE")" ]] || exit 3
RAILWAY_PROJECT_ID="${LIFE_MANAGER_RAILWAY_PROJECT_ID:-f9c524cb-ba4a-43bb-9639-ff736afd9ec1}"; RAILWAY_ENVIRONMENT="${LIFE_MANAGER_RAILWAY_ENVIRONMENT:-production}"; RAILWAY_SERVICE="${LIFE_MANAGER_POSTGRES_SERVICE:-Postgres-1nl0}"; TEMP_DIR="$(mktemp -d)";trap 'rm -rf "$TEMP_DIR"' EXIT
printf "\\set ON_ERROR_STOP on\n\\set tenant '%s'\n\\set attempt '%s'\n\\set day_id '%s'\n\\set day_digest '%s'\n\\set day_signature '%s'\n\\set funder '%s'\n\\set tokyo_day '%s'\n\\set day_evaluated '%s'\n\\set fresh_id '%s'\n\\set fresh_digest '%s'\n\\set signature '%s'\n\\pset tuples_only on\n\\pset format unaligned\nSELECT CASE WHEN EXISTS (SELECT 1 FROM public.lm_funder_submission_day_gates WHERE tenant_id=:'tenant' AND attempt_id=:'attempt'::uuid AND gate_id=:'day_id' AND gate_digest=:'day_digest' AND attestation_signature=:'day_signature' AND funder_id=:'funder' AND tokyo_day=:'tokyo_day'::date AND evaluated_at=:'day_evaluated'::timestamptz AND decision='allow' AND submit_allowed) AND EXISTS (SELECT 1 FROM public.lm_funder_asset_freshness_gates WHERE tenant_id=:'tenant' AND attempt_id=:'attempt'::uuid AND gate_id=:'fresh_id' AND gate_digest=:'fresh_digest' AND funder_id=:'funder' AND decision='allow' AND submit_allowed AND expires_at > now() AND attestation_signature=:'signature') THEN 'verified' ELSE 'rejected' END;\n" "$TENANT" "$ATTEMPT" "$DAY_ID" "$DAY_DIGEST" "$DAY_SIGNATURE" "$FUNDER" "$TOKYO_DAY" "$DAY_EVALUATED" "$FRESH_ID" "$FRESH_DIGEST" "$(jq -r '.attestation_signature' "$FRESH_GATE")" > "$TEMP_DIR/check.sql"
set +e; railway connect -p "$RAILWAY_PROJECT_ID" -e "$RAILWAY_ENVIRONMENT" "$RAILWAY_SERVICE" < "$TEMP_DIR/check.sql" > "$TEMP_DIR/result.log" 2>&1; CONNECT_EXIT=$?; set -e
cat "$TEMP_DIR/result.log"
[[ "$CONNECT_EXIT" -eq 0 ]] && ! grep -Eiq '(^|[[:space:]])(ERROR|FATAL):|psql: error|connection .* failed|server closed the connection|temporary service issue|open failed' "$TEMP_DIR/result.log" && grep -qx 'verified' "$TEMP_DIR/result.log"
