"use strict";
const test = require("node:test"); const assert = require("node:assert/strict"); const fs = require("node:fs"); const os = require("node:os"); const path = require("node:path"); const crypto = require("node:crypto");
const { collectAndWriteLocalAgentUsageBatch } = require("./cfo-local-agent-usage-batch-store.js");
const source = "life_manager_agent_usage", at = "2026-08-10T01:02:03Z";
const row = (event_id, extra = {}) => ({ version: 1, event_id, timestamp: at, loop: "gig", task_label: "gig-daily", provider: "codex", provider_name: "openai", model: "gpt-5.6", upstream_model: null, attempt: 1, status: "success", measurement: "provider_reported", tokens: { input: 1, cached_input: 0, cache_creation_input: 0, output: 2, reasoning_output: 0, total: 3 }, ...extra });
const lines = (...rows) => Buffer.from(`${rows.map(JSON.stringify).join("\n")}\n`); const hash = (bytes) => crypto.createHash("sha256").update(bytes).digest("hex");
test("publishes immutable content-addressed append batches and converges retries", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-batch-")), root = path.join(parent, "state"); try {
    const firstBytes = lines(row("a".repeat(24)), row("b".repeat(24), { loop: "connector", task_label: "connector-send", measurement: "unavailable", tokens: { input: null, cached_input: null, cache_creation_input: null, output: null, reasoning_output: null, total: null } }));
    const first = collectAndWriteLocalAgentUsageBatch(root, at, source, firstBytes, null), dir = path.join(root, "cfo/local-agent-usage", source), firstFile = path.join(dir, `${first.record_id}.json`), firstRecord = fs.readFileSync(firstFile);
    assert.deepEqual(Object.keys(first), ["record_id", "source_id", "byte_offset", "event_count", "mapping_id"]); assert.ok(Object.isFrozen(first)); assert.equal(hash(firstRecord), first.record_id); const firstJson = JSON.parse(firstRecord); assert.deepEqual(Object.keys(firstJson), ["schema_version", "collected_at", "mapping_id", "prior_source_state", "source_state", "events", "delta_counts", "coverage_exceptions"]); assert.deepEqual(Object.keys(firstJson.events[0]), ["schema_version", "source_ledger", "source_event_id", "runner_event_id", "occurred_at", "provider", "provider_name", "request_model", "upstream_model", "run", "financial_unit_id", "attribution_status", "measurement", "token_value_basis", "tokens", "coverage_status"]); assert.equal(firstJson.events.length, firstJson.delta_counts.accepted_rows); assert.equal(firstJson.source_state.byte_offset, first.byte_offset); assert.ok(["input", "context", "raw_row", "prompt", "response"].every((key) => !Object.hasOwn(firstJson, key)));
    const allBytes = Buffer.concat([firstBytes, lines(row("c".repeat(24)))]), second = collectAndWriteLocalAgentUsageBatch(root, at, source, allBytes, JSON.parse(firstRecord).source_state), secondPath = path.join(dir, `${second.record_id}.json`), secondBefore = fs.readFileSync(secondPath); assert.notEqual(second.record_id, first.record_id); assert.deepEqual(JSON.parse(secondBefore).prior_source_state, JSON.parse(firstRecord).source_state); assert.equal(second.event_count, 1); assert.deepEqual(collectAndWriteLocalAgentUsageBatch(root, at, source, allBytes, JSON.parse(firstRecord).source_state), second); assert.deepEqual(fs.readdirSync(dir).filter((name) => name.endsWith(".json")).sort(), [path.basename(firstFile), path.basename(secondPath)].sort());
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});
test("cleans pre-rename failures, keeps post-rename receipt, and validates before mutation", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-batch-")), root = path.join(parent, "state"), bytes = lines(row("d".repeat(24))); try {
    const stable = collectAndWriteLocalAgentUsageBatch(root, at, source, bytes, null), dir = path.join(root, "cfo/local-agent-usage", source), stablePath = path.join(dir, `${stable.record_id}.json`), stableBefore = fs.readFileSync(stablePath), prior = JSON.parse(stableBefore).source_state, nextBytes = Buffer.concat([bytes, lines(row("e".repeat(24)))]); assert.throws(() => collectAndWriteLocalAgentUsageBatch(root, at, source, nextBytes, prior, { fsyncImpl() { throw Error("HOSTILE"); } }), /cfo_local_agent_usage_batch_store_invalid:write_failed$/); assert.deepEqual(fs.readFileSync(stablePath), stableBefore); assert.equal(fs.readdirSync(dir).filter((name) => name.endsWith(".tmp")).length, 0);
    let failDirectory = true; const fsyncImpl = (fd) => { if (fs.fstatSync(fd).isDirectory() && failDirectory) { failDirectory = false; throw Error("HOSTILE"); } fs.fsyncSync(fd); }; const failed = () => collectAndWriteLocalAgentUsageBatch(root, at, source, nextBytes, prior, { fsyncImpl }); assert.throws(failed, /cfo_local_agent_usage_batch_store_invalid:write_failed$/); const published = fs.readdirSync(dir).filter((name) => name.endsWith(".json")); assert.equal(published.length, 2); const newName = published.find((name) => name !== path.basename(stablePath)); assert.ok(newName); assert.equal(hash(fs.readFileSync(path.join(dir, newName))), newName.slice(0, -5)); const retry = collectAndWriteLocalAgentUsageBatch(root, at, source, nextBytes, prior); assert.equal(retry.record_id, newName.slice(0, -5));
    const clean = path.join(parent, "untouched"), existing = path.join(parent, "existing"), aliases = ["/..", `${os.tmpdir()}/..`, `${parent}/nested/../untouched`], invalid = [[[clean, "bad", source, bytes, null], "cfo_local_agent_usage_batch_store_invalid:invalid_collected_at"], [[clean, at, source, bytes, null, { extra: 1 }], "cfo_local_agent_usage_batch_store_invalid:invalid_options"], [[clean, at, "HOSTILE_SOURCE", bytes, null], "cfo_local_agent_usage_cursor_invalid:invalid_source"], [[clean, at, source, "bytes", null], "cfo_local_agent_usage_cursor_invalid:invalid_bytes"]]; fs.mkdirSync(existing); fs.chmodSync(existing, 0o755); const existingMode = fs.statSync(existing).mode & 0o777; for (const stateRoot of ["relative", ...aliases]) assert.throws(() => collectAndWriteLocalAgentUsageBatch(stateRoot, at, source, bytes, null), (error) => error.message === "cfo_local_agent_usage_batch_store_invalid:invalid_state_root" && !error.message.includes("HOSTILE")); for (const [args, message] of invalid) assert.throws(() => collectAndWriteLocalAgentUsageBatch(...args), (error) => error.message === message && !error.message.includes("HOSTILE")); assert.equal(fs.existsSync(clean), false); collectAndWriteLocalAgentUsageBatch(existing, at, source, bytes, null); assert.equal(fs.statSync(existing).mode & 0o777, existingMode);
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});
