"use strict";
const assert = require("node:assert/strict"); const crypto = require("node:crypto"); const fs = require("node:fs"); const os = require("node:os"); const path = require("node:path"); const test = require("node:test");
const { captureLatestAnthropicSubscriptionReceipt } = require("./cfo-anthropic-receipt-local-source.js");
const body = "RECEIPT_ID_SENTINEL INVOICE_ID_SENTINEL payment@example.invalid https://private.invalid/receipt Receipt from Anthropic, PBC $220.00 Paid August 10, 2026 Aug 10–Sep 10, 2026 Max plan - 20x Qty 1 $200.00 Subtotal $200.00 Total excluding tax $200.00 JCT - Japan (10%) $20.00 Total $220.00 Amount paid $220.00 RAW_BODY_FRAGMENT";
const hash = value => crypto.createHash("sha256").update(value, "utf8").digest("hex"); const mode = value => fs.statSync(value).mode & 0o777; const dir = root => path.join(root, "cfo", "provider-billing", "anthropic");
const mail = (value = body, calls = { count: 0 }, frozen = true) => ({ calls, mail: { async readLatestAnthropicSubscriptionReceipt() { calls.count += 1; const evidence = value === null ? null : { source: "anthropic_subscription_receipt_gmail", receivedAtLocal: "2026-08-10 10:00", body: value }; return frozen && evidence ? Object.freeze(evidence) : evidence; } } });
const deepFrozen = value => value && typeof value === "object" ? Object.isFrozen(value) && Object.values(value).every(deepFrozen) : true;

test("captures one exact immutable receipt, then accepts only the byte-identical existing record", async () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-anthropic-capture-")), root = path.join(parent, "state"), firstMail = mail(), expected = { schema_version: "lm_subscription_receipt_v1", provider: "anthropic", plan: "max_20x", billing_period_start: "2026-08-10", billing_period_end: "2026-09-10", subtotal: "200.00", tax: "20.00", total: "220.00", currency: "USD", paid_date: "2026-08-10", source_hash: `sha256:${hash(body)}`, evidence_status: "provider_receipt" };
  try { const first = await captureLatestAnthropicSubscriptionReceipt({ stateRoot: root, mail: firstMail.mail }); assert.equal(first.status, "appended"); assert.deepEqual(first.confirmed, expected); assert.deepEqual(Object.keys(first), ["status", "record_id", "confirmed"]); assert.ok(deepFrozen(first)); assert.equal(firstMail.calls.count, 1); const record = path.join(dir(root), `${hash(body)}.json`), before = fs.readFileSync(record); assert.deepEqual(JSON.parse(before), expected); assert.equal(mode(record), 0o600); for (const item of [root, path.join(root, "cfo"), path.join(root, "cfo", "provider-billing"), dir(root)]) assert.equal(mode(item), 0o700); assert.doesNotMatch(JSON.stringify(first), /RECEIPT_ID|INVOICE_ID|payment@example|private\.invalid|RAW_BODY_FRAGMENT/); assert.doesNotMatch(before.toString(), /RECEIPT_ID|INVOICE_ID|payment@example|private\.invalid|RAW_BODY_FRAGMENT/); assert.doesNotMatch(record, /RECEIPT_ID|INVOICE_ID|payment@example|private\.invalid|RAW_BODY_FRAGMENT/); const secondMail = mail(); const second = await captureLatestAnthropicSubscriptionReceipt({ stateRoot: root, mail: secondMail.mail }); assert.equal(second.status, "existing"); assert.deepEqual(second.confirmed, expected); assert.deepEqual(fs.readFileSync(record), before); assert.equal(secondMail.calls.count, 1); } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});

test("rejects money/layout/source truth with fixed redacted errors and preserves conflicts", async () => {
  const cases = [["wrong plan", body.replace("Max plan - 20x", "Max plan - 5x"), "receipt_format"], ["wrong next-month period", body.replace("Aug 10–Sep 10", "Aug 10–Oct 10"), "receipt_period"], ["rolled next-month period", body.replace("Paid August 10, 2026", "Paid January 31, 2026").replace("Aug 10–Sep 10, 2026", "Jan 31–Mar 3, 2026"), "receipt_period"], ["reversed labels", body.replace("Subtotal $200.00 Total excluding tax $200.00", "Total excluding tax $200.00 Subtotal $200.00"), "receipt_format"], ["duplicate amount label", body.replace("Subtotal $200.00", "Subtotal $200.00 Subtotal $200.00"), "receipt_format"], ["unsafe/invalid amount", body.replace("$220.00 Paid", "$90071992547409.92 Paid"), "receipt_amount"], ["tax mismatch", body.replace("JCT - Japan (10%) $20.00", "JCT - Japan (10%) $21.00"), "receipt_amount"], ["total mismatch", body.replace("Total $220.00", "Total $221.00"), "receipt_amount"], ["unapproved consistent price", body.replaceAll("$200.00", "$210.00").replaceAll("$20.00", "$21.00").replaceAll("$220.00", "$231.00"), "receipt_amount"], ["source unavailable", null, "source_unavailable"], ["mutable evidence", body, "receipt_format"]];
  const sinks = [console.log, console.error, console.warn]; let logs = 0; console.log = console.error = console.warn = () => { logs += 1; };
  try { for (const [name, value, reason] of cases) { const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-anthropic-fail-")), root = path.join(parent, "state"), fake = mail(value, undefined, name !== "mutable evidence"); logs = 0; try { await assert.rejects(captureLatestAnthropicSubscriptionReceipt({ stateRoot: root, mail: fake.mail }), error => error instanceof Error && error.message === `cfo_anthropic_receipt_capture_invalid:${reason}`, name); assert.equal(logs, 0, name); assert.equal(fs.existsSync(dir(root)), false, name); } finally { fs.rmSync(parent, { recursive: true, force: true }); } } const externalParent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-anthropic-external-")), externalRoot = path.join(externalParent, "state"), externalMail = { async readLatestAnthropicSubscriptionReceipt() { throw new Error("cfo_anthropic_receipt_capture_invalid:RAW_SECRET_SENTINEL"); } }; logs = 0; try { await assert.rejects(captureLatestAnthropicSubscriptionReceipt({ stateRoot: externalRoot, mail: externalMail }), error => error instanceof Error && error.message === "cfo_anthropic_receipt_capture_invalid:capture_failed"); assert.equal(logs, 0); assert.equal(fs.existsSync(dir(externalRoot)), false); } finally { fs.rmSync(externalParent, { recursive: true, force: true }); } } finally { [console.log, console.error, console.warn] = sinks; }
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-anthropic-conflict-")), root = path.join(parent, "state"), target = path.join(dir(root), `${hash(body)}.json`), conflict = Buffer.from("{\"CONFLICT_SECRET\":true}\n"); try { fs.mkdirSync(dir(root), { recursive: true, mode: 0o700 }); fs.writeFileSync(target, conflict, { mode: 0o600 }); await assert.rejects(captureLatestAnthropicSubscriptionReceipt({ stateRoot: root, mail: mail().mail }), /^Error: cfo_anthropic_receipt_capture_invalid:record_conflict$/); assert.deepEqual(fs.readFileSync(target), conflict); } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});
