"use strict";
const test = require("node:test"), assert = require("node:assert/strict"), fs = require("node:fs"), os = require("node:os"), path = require("node:path");
const { runLocalAgentUsageCollection } = require("./cfo-local-agent-usage-runner.js");
const { captureLocalAgentUsageCollection: captureSpan } = require("./cfo-local-agent-usage-span.js");
const LM = "life_manager_agent_usage", AN = "anicca_agent_usage", at = "2026-08-11T01:02:03.000Z";
const attemptId = { [LM]: "1".repeat(24), [AN]: "2".repeat(24) }, attempt = id => ({ version: 1, event_id: attemptId[id], timestamp: at, loop: "gig", task_label: "daily", attempt: 1, provider: "codex", model: "gpt-5" });
const event = (id, status = "success") => ({ schema_version: 1, source_ledger: "local_agent_usage", source_event_id: `local_agent_usage:${attemptId[id]}`, runner_event_id: attemptId[id], occurred_at: at, provider: "codex", provider_name: "openai", request_model: "gpt-5", upstream_model: null, run: { attempt: 1, loop: "gig", status, task_label: "daily" }, financial_unit_id: "life_manager_saas", attribution_status: "attributed", measurement: "provider_reported", token_value_basis: "runner_normalized_provider_usage", tokens: { cache_creation_input: 0, cached_input: 0, input: 0, output: 0, reasoning_output: 0, total: 0 }, coverage_status: "covered" });
const zeroCounts = () => ({ discovered_rows: 0, accepted_rows: 0, duplicate_rows: 0, conflicting_rows: 0, missing_usage_rows: 0, runner_collision_groups: 0, attributed_rows: 0, unattributed_rows: 0 });
const emptyChain = id => ({ status: "empty", source_state: null, record_count: 0, events: [], counts: zeroCounts(), coverage_exceptions: [] }), readyChain = (id, item) => ({ status: "ready", source_state: { schema_version: 1, source_id: id, byte_offset: 0, prefix_sha256: "0".repeat(64), observed_file_size: 0 }, record_count: 1, events: [item], counts: { discovered_rows: 1, accepted_rows: 1, duplicate_rows: 0, conflicting_rows: 0, missing_usage_rows: 0, runner_collision_groups: 0, attributed_rows: 1, unattributed_rows: 0 }, coverage_exceptions: [] });
function captureOptions(attempts, completions) { const f = options({ readFile: file => { f.calls.push(["read", file]); const id = file.includes("/tmp/cfo-state/") ? LM : AN; return file.endsWith("agent-usage-attempts.jsonl") ? attempts[id] : Buffer.from("x\n"); }, readChain: (root, id) => { f.calls.push(["chain", root, id]); f.chainReads = f.chainReads || {}; const post = f.chainReads[id]++; return post ? (completions[id] ? readyChain(id, completions[id]) : emptyChain(id)) : emptyChain(id); } }); f.chainReads = { [LM]: 0, [AN]: 0 }; return f; }
const prior = { schema_version: 1, source_id: LM, byte_offset: 4, prefix_sha256: "a".repeat(64), observed_file_size: 4 };
const chain = (id, state = null) => state ? { ...emptyChain(id), status: "ready", source_state: state } : emptyChain(id);
const receipt = (id, bytes, offset = bytes.length) => ({ record_id: "b".repeat(64), source_id: id, byte_offset: offset, event_count: 0, mapping_id: "local_agent_usage_v1" });
const published = id => ({ source_id: id, status: "published", record_id: "b".repeat(64), byte_offset: 0, event_count: 0, mapping_id: "local_agent_usage_v1", coverage_exceptions: [] }), failedSource = (id, exception) => ({ source_id: id, status: "unavailable", record_id: null, byte_offset: null, event_count: null, mapping_id: null, coverage_exceptions: [exception] });
const spanReceipt = (status, sources, coverage_exceptions) => ({ status, collected_at: at, sources: sources || [published(LM), published(AN)], coverage_exceptions: coverage_exceptions || [] });
const modernReceipt = (capture_counts, coverage_exceptions = capture_counts.coverage_exceptions) => ({ status: capture_counts.status === "complete" ? "complete" : "partial", collected_at: at, sources: [published(LM), published(AN)], capture_counts, coverage_exceptions });
const modernComplete = { status: "complete", source_count: 2, reconciled_source_count: 2, attempted_rows: 2, success_rows: 2, failed_rows: 0, missing_completion_rows: 0, unmatched_completion_rows: 0, duplicate_attempt_rows: 0, conflicting_attempt_rows: 0, ambiguous_completion_rows: 0, coverage_exceptions: [] }, modernPartial = { ...modernComplete, status: "partial", success_rows: 1, missing_completion_rows: 1, coverage_exceptions: ["missing_completion"] }, modernUnavailable = { status: "unavailable", source_count: 2, reconciled_source_count: 1, attempted_rows: null, success_rows: null, failed_rows: null, missing_completion_rows: null, unmatched_completion_rows: null, duplicate_attempt_rows: null, conflicting_attempt_rows: null, ambiguous_completion_rows: null, coverage_exceptions: ["attempt_source_unreadable"] };
function options(overrides = {}) {
  const calls = [], clocks = { count: 0 }, chainReads = { [LM]: 0, [AN]: 0 }, base = {
    home: "/tmp/cfo-home", env: { LIFE_MANAGER_STATE_HOME: "/tmp/cfo-state" }, now: () => { clocks.count += 1; return new Date(at); },
    readChain: (root, id) => { calls.push(["chain", root, id]); return chainReads[id]++ ? readyChain(id, event(id)) : chain(id, id === LM ? prior : null); },
    readFile: file => { calls.push(["read", file]); if (file.endsWith("agent-usage-attempts.jsonl")) { const id = file.includes("cfo-state") ? LM : AN; return Buffer.from(JSON.stringify(attempt(id)) + "\n"); } return Buffer.from("12345"); },
    writeBatch: (root, collectedAt, id, bytes, state) => { calls.push(["write", root, collectedAt, id, bytes, state]); return receipt(id, bytes); },
  };
  return { calls, clocks, options: { ...base, ...overrides } };
}
test("publishes both fixed ledgers once with one clock, prior cursors, and a frozen content-free receipt", () => {
  const f = options(), got = runLocalAgentUsageCollection(f.options);
  assert.equal(f.clocks.count, 1);
  assert.deepEqual(f.calls.map(call => [call[0], call[0] === "chain" ? call[2] : call[0] === "read" ? call[1] : call[3]]), [["chain", LM], ["read", "/tmp/cfo-state/telemetry/agent-usage.jsonl"], ["write", LM], ["chain", AN], ["read", "/tmp/cfo-home/.local/state/anicca/telemetry/agent-usage.jsonl"], ["write", AN], ["read", "/tmp/cfo-state/telemetry/agent-usage-attempts.jsonl"], ["chain", LM], ["read", "/tmp/cfo-home/.local/state/anicca/telemetry/agent-usage-attempts.jsonl"], ["chain", AN]]);
  assert.deepEqual(f.calls.filter(call => call[0] === "write").map(call => call[5]), [prior, null]);
  assert.deepEqual(got, { status: "complete", collected_at: at, sources: [
    { source_id: LM, status: "published", record_id: "b".repeat(64), byte_offset: 5, event_count: 0, mapping_id: "local_agent_usage_v1", coverage_exceptions: [] },
    { source_id: AN, status: "published", record_id: "b".repeat(64), byte_offset: 5, event_count: 0, mapping_id: "local_agent_usage_v1", coverage_exceptions: [] },
  ], capture_counts: { status: "complete", source_count: 2, reconciled_source_count: 2, attempted_rows: 2, success_rows: 2, failed_rows: 0, missing_completion_rows: 0, unmatched_completion_rows: 0, duplicate_attempt_rows: 0, conflicting_attempt_rows: 0, ambiguous_completion_rows: 0, coverage_exceptions: [] }, coverage_exceptions: [] });
  assert.deepEqual(Object.keys(got).sort(), ["capture_counts", "collected_at", "coverage_exceptions", "sources", "status"].sort()); assert.equal(got.capture_counts.success_rows + got.capture_counts.failed_rows + got.capture_counts.missing_completion_rows, got.capture_counts.attempted_rows); assert.ok(Object.isFrozen(got) && Object.isFrozen(got.capture_counts) && Object.isFrozen(got.sources) && got.sources.every(source => Object.isFrozen(source) && Object.isFrozen(source.coverage_exceptions)));
  assert.doesNotMatch(JSON.stringify(got), /12345|HOSTILE|payload|prompt|secret/i);
});
test("isolates an unreadable source and lets the other source publish without leaking the thrown sentinel", () => {
  const f = options({ readFile: file => { f.calls.push(["read", file]); if (file.startsWith("/tmp/cfo-state/")) throw new Error("HOSTILE_PATH_RAW"); if (file.endsWith("agent-usage-attempts.jsonl")) return Buffer.from(JSON.stringify(attempt(AN)) + "\n"); return Buffer.from("safe"); }, writeBatch: (root, collectedAt, id, bytes, state) => { f.calls.push(["write", root, collectedAt, id, bytes, state]); return receipt(id, bytes); } });
  const got = runLocalAgentUsageCollection(f.options), failed = got.sources[0], published = got.sources[1];
  assert.equal(got.status, "partial"); assert.deepEqual(got.coverage_exceptions, ["attempt_source_unreadable", "source_unreadable"]); assert.deepEqual(got.capture_counts, { status: "unavailable", source_count: 2, reconciled_source_count: 1, attempted_rows: null, success_rows: null, failed_rows: null, missing_completion_rows: null, unmatched_completion_rows: null, duplicate_attempt_rows: null, conflicting_attempt_rows: null, ambiguous_completion_rows: null, coverage_exceptions: ["attempt_source_unreadable"] });
  assert.deepEqual(failed, { source_id: LM, status: "unavailable", record_id: null, byte_offset: null, event_count: null, mapping_id: null, coverage_exceptions: ["source_unreadable"] });
  assert.equal(published.status, "published"); assert.equal(f.calls.filter(call => call[0] === "write").length, 1); assert.equal(f.calls.filter(call => call[0] === "write")[0][3], AN);
  assert.doesNotMatch(JSON.stringify(got), /HOSTILE_PATH_RAW|safe|agent-usage\.jsonl/i);
});
test("turns malformed dependencies into local-state failures, preserves null-only empty writes, accepts truncation, and rejects bad arguments before effects", () => {
  for (const kind of ["chain", "writer"]) {
    const f = options(kind === "chain" ? { readChain: (root, id) => id === LM ? { ...chain(LM, prior), hostile: "HOSTILE_CHAIN" } : chain(AN, null) } : { readChain: (root, id) => chain(id, null), writeBatch: (root, atValue, id, bytes, state) => id === AN ? { ...receipt(id, bytes), source_id: "HOSTILE_SOURCE", extra: "HOSTILE_WRITER" } : receipt(id, bytes) });
    const got = runLocalAgentUsageCollection(f.options), failed = got.sources[kind === "chain" ? 0 : 1], other = got.sources[kind === "chain" ? 1 : 0];
    assert.equal(failed.status, "failed"); assert.deepEqual(failed.coverage_exceptions, ["local_state_failure"]); assert.equal(other.status, "published");
    if (kind === "chain") assert.equal(f.calls.filter(call => call[0] === "read" && call[1].includes("life-manager")).length, 0);
    assert.doesNotMatch(JSON.stringify(got), /HOSTILE_CHAIN|HOSTILE_SOURCE|HOSTILE_WRITER/);
  }
  const trunc = options({ readFile: () => Buffer.from("12"), writeBatch: (root, atValue, id, bytes, state) => receipt(id, bytes, state ? state.byte_offset : bytes.length) }), truncated = runLocalAgentUsageCollection(trunc.options);
  assert.equal(truncated.sources[0].status, "published"); assert.equal(truncated.sources[0].byte_offset, 4);
  const effects = { calls: 0 }, seam = () => { effects.calls += 1; throw new Error("HOSTILE_EFFECT"); }, bad = [
    [{ extra: 1 }, "invalid_options"], [{ home: "/tmp/cfo-home/..", now: seam }, "invalid_home"], [{ env: { LIFE_MANAGER_STATE_HOME: "relative" }, now: seam }, "invalid_state_root"], [{ now: () => new Date("invalid") }, "invalid_clock"],
  ];
  for (const [input, reason] of bad) assert.throws(() => runLocalAgentUsageCollection({ ...input, readChain: seam, readFile: seam, writeBatch: seam }), error => error.message === `cfo_local_agent_usage_runner_invalid:${reason}`);
  assert.equal(effects.calls, 0);
});
test("rejects a coercible hostile writer record ID without leaking it", () => {
  const hostile = { toString: () => "b".repeat(64), secret: "HOSTILE_RECORD_ID" }, f = options({ readChain: (root, id) => chain(id, null), writeBatch: (root, atValue, id, bytes) => id === LM ? { ...receipt(id, bytes), record_id: hostile } : receipt(id, bytes) }), got = runLocalAgentUsageCollection(f.options);
  assert.equal(got.sources[0].status, "failed"); assert.deepEqual(got.sources[0].coverage_exceptions, ["local_state_failure"]); assert.equal(got.sources[1].status, "published"); assert.doesNotMatch(JSON.stringify(got), /HOSTILE_RECORD_ID/);
});
test("names a durable attempt with no post-write completion", () => { const attempts = { [LM]: Buffer.from(JSON.stringify(attempt(LM)) + "\n"), [AN]: Buffer.from(JSON.stringify(attempt(AN)) + "\n") }, f = captureOptions(attempts, { [AN]: event(AN) }), got = runLocalAgentUsageCollection(f.options); assert.equal(got.status, "partial"); assert.deepEqual(got.capture_counts, { status: "partial", source_count: 2, reconciled_source_count: 2, attempted_rows: 2, success_rows: 1, failed_rows: 0, missing_completion_rows: 1, unmatched_completion_rows: 0, duplicate_attempt_rows: 0, conflicting_attempt_rows: 0, ambiguous_completion_rows: 0, coverage_exceptions: ["missing_completion"] }); assert.deepEqual(got.coverage_exceptions, ["missing_completion"]); assert.equal(got.capture_counts.success_rows + got.capture_counts.failed_rows + got.capture_counts.missing_completion_rows, got.capture_counts.attempted_rows); const firstAttempt = f.calls.findIndex(call => call[0] === "read" && call[1].endsWith("agent-usage-attempts.jsonl")), lastWrite = f.calls.map(call => call[0]).lastIndexOf("write"), lastLmChain = f.calls.reduce((last, call, index) => call[0] === "chain" && call[2] === LM ? index : last, -1); assert.ok(firstAttempt > lastWrite && lastLmChain > firstAttempt); });
test("names every attempt-source boundary without exposing sentinels", () => {
  const valid = Buffer.from(JSON.stringify(attempt(AN)) + "\n"), malformed = [[Buffer.alloc(0), "capture_not_started"], [null, "capture_not_started"], [Buffer.from("\n"), "attempt_source_invalid"], [Buffer.from(JSON.stringify(attempt(LM)) + "\n\n"), "attempt_source_invalid"], [Buffer.from("{\n"), "attempt_source_invalid"], [Buffer.from(JSON.stringify(attempt(LM))), "attempt_source_invalid"], ["not-buffer", "attempt_source_invalid"], [Buffer.from("{}\n"), "local_state_failure"]];
  for (const [bytes, expected] of malformed) { const attempts = { [LM]: bytes, [AN]: valid }, f = captureOptions(attempts, { [AN]: event(AN) }); f.options.readFile = file => { f.calls.push(["read", file]); if (file.endsWith("agent-usage-attempts.jsonl") && file.includes("cfo-state")) { if (bytes === null) throw Object.assign(new Error("HOSTILE_ENOENT"), { code: "ENOENT" }); return bytes; } return file.endsWith("agent-usage-attempts.jsonl") ? valid : Buffer.from("x\n"); }; const got = runLocalAgentUsageCollection(f.options); assert.deepEqual(got.coverage_exceptions, [expected]); assert.doesNotMatch(JSON.stringify(got), /HOSTILE_ENOENT|HOSTILE_READ|prompt|token|cost|path/i); }
  const f = captureOptions({ [LM]: Buffer.alloc(0), [AN]: valid }, { [AN]: event(AN) }); f.options.readFile = file => { f.calls.push(["read", file]); if (file.endsWith("agent-usage-attempts.jsonl") && file.includes("cfo-state")) throw Object.assign(new Error("HOSTILE_EIO"), { code: "EIO" }); return file.endsWith("agent-usage-attempts.jsonl") ? valid : Buffer.from("x\n"); }; assert.deepEqual(runLocalAgentUsageCollection(f.options).coverage_exceptions, ["attempt_source_unreadable"]);
});
test("maps falsy attempt-read throws to one fixed unreadable exception", () => { const valid = Buffer.from(JSON.stringify(attempt(AN)) + "\n"); for (const thrown of [undefined, null, false, 0, ""]) { const f = captureOptions({ [LM]: valid, [AN]: valid }, { [AN]: event(AN) }); f.options.readFile = file => { f.calls.push(["read", file]); if (file.endsWith("agent-usage-attempts.jsonl") && file.includes("cfo-state")) throw thrown; return file.endsWith("agent-usage-attempts.jsonl") ? valid : Buffer.from("x\n"); }; const got = runLocalAgentUsageCollection(f.options); assert.deepEqual(got.coverage_exceptions, ["attempt_source_unreadable"]); assert.doesNotMatch(JSON.stringify(got), /HOSTILE/); } });
test("span validates capture counts, emits only numeric count attributes, and preserves old receipts", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-span-counts-")), input = { env: { LIFE_MANAGER_STATE_HOME: root } }, base = ["status", "source_count", "reconciled_source_count", "coverage_exception_count"].map(key => `cfo.usage.capture.${key}`), names = ["attempted_rows", "success_rows", "failed_rows", "missing_completion_rows", "unmatched_completion_rows", "duplicate_attempt_rows", "conflicting_attempt_rows", "ambiguous_completion_rows"].map(key => `cfo.usage.capture.${key}`), accepted = [modernReceipt(modernComplete), modernReceipt(modernPartial), modernReceipt(modernUnavailable)];
  try { for (const expected of accepted) { const got = await captureSpan(async () => expected, input), record = JSON.parse(fs.readFileSync(path.join(root, "telemetry", "cfo-local-agent-usage-otel-spans.jsonl"), "utf8").trim().split("\n").pop()), attrs = record.attributes, keys = Object.keys(attrs).filter(key => key.startsWith("cfo.usage.capture.")); assert.deepEqual(got, expected); assert.deepEqual(keys.sort(), [...base, ...(expected.capture_counts.status === "unavailable" ? [] : names), ...(expected.capture_counts.coverage_exceptions.length ? ["cfo.usage.capture.coverage_exceptions"] : [])].sort()); assert.equal(attrs["cfo.usage.capture.status"], expected.capture_counts.status); assert.equal(attrs["cfo.usage.capture.source_count"], 2); assert.equal(attrs["cfo.usage.capture.reconciled_source_count"], expected.capture_counts.reconciled_source_count); assert.equal(attrs["cfo.usage.capture.coverage_exception_count"], expected.capture_counts.coverage_exceptions.length); for (const key of names) if (expected.capture_counts[key.slice("cfo.usage.capture.".length)] !== null) assert.equal(attrs[key], expected.capture_counts[key.slice("cfo.usage.capture.".length)]); assert.doesNotMatch(JSON.stringify(record), /token|cost|secret|private/i); }
    const old = spanReceipt("complete"); await captureSpan(async () => old, input); const oldRecord = JSON.parse(fs.readFileSync(path.join(root, "telemetry", "cfo-local-agent-usage-otel-spans.jsonl"), "utf8").trim().split("\n").pop()); assert.equal(Object.keys(oldRecord.attributes).some(key => key.startsWith("cfo.usage.capture.")), false);
    const accessor = { ...modernComplete }; Object.defineProperty(accessor, "attempted_rows", { enumerable: true, get: () => 2 }); const proxied = new Proxy({ ...modernComplete }, {}), invalid = [
      { ...modernComplete, coverage_exceptions: ["missing_completion"] }, { ...modernPartial, failed_rows: null }, { ...modernPartial, missing_completion_rows: 2 }, { ...modernComplete, source_count: 1 }, { ...modernComplete, extra: 1 }, accessor, proxied, { ...modernComplete, attempted_rows: Number.MAX_SAFE_INTEGER + 1 }, { ...modernPartial, coverage_exceptions: ["attempt_source_invalid"] }, { ...modernUnavailable, attempted_rows: 0 }, { ...modernUnavailable, coverage_exceptions: ["missing_completion"] }, { ...modernUnavailable, reconciled_source_count: 2, coverage_exceptions: ["attempt_source_unreadable"] },
    ]; for (const capture_counts of invalid) await assert.rejects(() => captureSpan(async () => modernReceipt(capture_counts), input), error => error.message === "cfo_local_agent_usage_span_failed:invalid_receipt");
  } finally { fs.rmSync(root, { recursive: true, force: true }); }
});
test("span accepts legacy and capture-only unions and rejects malformed unions", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-span-")), input = { env: { LIFE_MANAGER_STATE_HOME: root } }, accepted = [spanReceipt("complete"), spanReceipt("partial", [failedSource(LM, "source_unreadable"), published(AN)], ["source_unreadable"]), spanReceipt("partial", null, ["local_state_failure"]), spanReceipt("partial", [failedSource(LM, "source_unreadable"), published(AN)], ["missing_completion", "source_unreadable"])];
  try { for (const expected of accepted) { const got = await captureSpan(async () => expected, input), record = JSON.parse(fs.readFileSync(path.join(root, "telemetry", "cfo-local-agent-usage-otel-spans.jsonl"), "utf8").trim().split("\n").pop()); assert.deepEqual(got, expected); assert.equal(record.attributes["cfo.usage.collection.coverage_exception_count"], expected.coverage_exceptions.length); if (expected.coverage_exceptions.length) { assert.deepEqual(record.attributes["cfo.usage.collection.coverage_exceptions"], expected.coverage_exceptions); assert.equal(record.attributes["error.type"], "collection_partial"); } assert.doesNotMatch(JSON.stringify(record), /token|cost|secret|private/i); } for (const bad of [spanReceipt("partial", [failedSource(LM, "source_unreadable"), published(AN)], []), spanReceipt("partial", null, ["unknown_capture"]), spanReceipt("partial", null, ["missing_completion", "missing_completion"]), spanReceipt("partial", null, ["unmatched_completion", "missing_completion"])]) await assert.rejects(() => captureSpan(async () => bad, input), error => error.message === "cfo_local_agent_usage_span_failed:invalid_receipt" && !/token|cost|secret|private|unknown_capture/.test(error.message)); } finally { fs.rmSync(root, { recursive: true, force: true }); }
});
