"use strict";
const test = require("node:test"), assert = require("node:assert/strict");
const { reconcileLocalAgentCapture: reconcile } = require("./cfo-local-agent-capture-reconciliation.js");
const A = "a".repeat(24), B = "b".repeat(24), C = "c".repeat(24), D = "d".repeat(24), E = "e".repeat(24);
const attempt = (event_id, timestamp, extra = {}) => ({ version: 1, event_id, timestamp, loop: "gig", task_label: "daily", attempt: 1, provider: "codex", model: "gpt-5", ...extra });
const event = (runner_event_id, occurred_at, status = "success", extra = {}) => ({ schema_version: 1, source_ledger: "local_agent_usage", source_event_id: `local_agent_usage:${runner_event_id}:${occurred_at}`, runner_event_id, occurred_at, provider: "codex", provider_name: "openai", request_model: "gpt-5", upstream_model: null, run: { attempt: 1, loop: "gig", status, task_label: "daily" }, financial_unit_id: "life_manager_saas", attribution_status: "attributed", measurement: "provider_reported", token_value_basis: "runner_normalized_provider_usage", tokens: { cache_creation_input: 0, cached_input: 0, input: 0, output: 0, reasoning_output: 0, total: 0 }, coverage_status: "covered", ...extra });
const missing = (id, time) => event(id, time, "success", { coverage_status: "missing_usage", measurement: "unavailable", token_value_basis: "unavailable", tokens: Object.fromEntries(["cache_creation_input", "cached_input", "input", "output", "reasoning_output", "total"].map(key => [key, null])) });
const chain = (events = [], source_id = "anicca_agent_usage", coverage_exceptions = []) => {
  const runners = new Map(); events.forEach(item => { const ids = runners.get(item.runner_event_id) || new Set(); ids.add(item.source_event_id); runners.set(item.runner_event_id, ids); });
  const attributed = events.filter(item => item.attribution_status === "attributed").length;
  const counts = { discovered_rows: events.length, accepted_rows: events.length, duplicate_rows: 0, conflicting_rows: 0, missing_usage_rows: events.filter(item => item.coverage_status === "missing_usage").length, runner_collision_groups: [...runners.values()].filter(ids => ids.size > 1).length, attributed_rows: attributed, unattributed_rows: events.length - attributed };
  const derived = [...coverage_exceptions]; if (counts.missing_usage_rows) derived.push("missing_usage"); if (counts.runner_collision_groups) derived.push("runner_identity_collision"); if (counts.unattributed_rows) derived.push("unattributed_usage"); if (counts.conflicting_rows) derived.push("conflicting_usage");
  return { status: "ready", source_state: { schema_version: 1, source_id, byte_offset: 0, prefix_sha256: "0".repeat(64), observed_file_size: 0 }, record_count: events.length, events, counts, coverage_exceptions: [...new Set(derived)].sort() };
};
const emptyChain = (events = []) => ({ ...chain(events), status: "empty", source_state: null, record_count: 0 });
const invalid = (rows, source = "anicca_agent_usage", usage = chain()) => assert.throws(() => reconcile(source, rows, usage), error => error.message.startsWith("cfo_local_agent_capture_invalid:") && !error.message.includes("HOSTILE_SECRET"));
const t0 = "2026-08-11T01:00:00.000000+00:00", t1 = "2026-08-11T01:01:00.000Z", t2 = "2026-08-11T01:02:00.000Z", t3 = "2026-08-11T01:03:00.000Z";

test("normal rows reconcile to the exact frozen receipt", () => {
  const got = reconcile("anicca_agent_usage", [attempt(A, t0), attempt(B, t1), attempt(C, t2), attempt(D, t3)], chain([event(A, "2026-08-11T01:00:10.000Z"), event(B, "2026-08-11T01:01:10.000Z", "failed"), missing(C, "2026-08-11T00:59:00.000Z"), event(D, "2026-08-11T01:02:30.000Z"), event(E, "2026-08-11T01:04:00.000Z")], "anicca_agent_usage", ["missing_usage"]));
  const expected = { schema_version: 1, source_id: "anicca_agent_usage", status: "partial", cutover_at: t0, attempted_rows: 4, success_rows: 1, failed_rows: 1, missing_completion_rows: 2, unmatched_completion_rows: 2, duplicate_attempt_rows: 0, conflicting_attempt_rows: 0, ambiguous_completion_rows: 0, coverage_exceptions: ["missing_completion", "unmatched_completion", "usage_chain_incomplete"] };
  assert.deepEqual(got, expected); assert.equal(got.success_rows + got.failed_rows + got.missing_completion_rows, got.attempted_rows); assert.ok(Object.isFrozen(got) && Object.isFrozen(got.coverage_exceptions));
});
test("matches a normalized completion at the same millisecond", () => { const raw = "2026-08-11T01:05:00.123456Z"; const got = reconcile("anicca_agent_usage", [attempt(A, raw)], chain([event(A, "2026-08-11T01:05:00.123Z")])); assert.equal(got.cutover_at, raw); assert.equal(got.status, "complete"); });
test("empty capture is explicit and ignores historical completions", () => { const got = reconcile("anicca_agent_usage", [], chain([event(A, "2026-08-11T00:59:00.000Z")])); assert.deepEqual(got, { schema_version: 1, source_id: "anicca_agent_usage", status: "empty", cutover_at: null, attempted_rows: 0, success_rows: 0, failed_rows: 0, missing_completion_rows: 0, unmatched_completion_rows: 0, duplicate_attempt_rows: 0, conflicting_attempt_rows: 0, ambiguous_completion_rows: 0, coverage_exceptions: ["capture_not_started"] }); });
test("deduplicates identical attempts and excludes conflicting groups", () => { const duplicate = reconcile("anicca_agent_usage", [attempt(A, t0), attempt(A, t0)], chain([event(A, "2026-08-11T01:00:01.000Z")])); assert.deepEqual([duplicate.attempted_rows, duplicate.success_rows, duplicate.duplicate_attempt_rows, duplicate.coverage_exceptions], [1, 1, 1, ["duplicate_attempt"]]); const conflict = reconcile("anicca_agent_usage", [attempt(A, t0), attempt(A, t0), attempt(A, t0, { task_label: "other" })], emptyChain()); assert.deepEqual([conflict.attempted_rows, conflict.conflicting_attempt_rows, conflict.duplicate_attempt_rows, conflict.coverage_exceptions], [0, 3, 0, ["conflicting_attempt"]]); });
test("counts every completion in an ambiguous match", () => { const got = reconcile("anicca_agent_usage", [attempt(A, t0)], chain([event(A, "2026-08-11T01:00:01.000Z"), event(A, "2026-08-11T01:00:02.000Z")])); assert.deepEqual([got.missing_completion_rows, got.ambiguous_completion_rows, got.status], [1, 2, "partial"]); });
test("rejects a ready chain from another source", () => invalid([attempt(A, t0)], "anicca_agent_usage", chain([event(A, "2026-08-11T01:00:01.000Z")], "life_manager_agent_usage")));
test("redacts hostile attempt and event shapes", () => { const accessor = attempt(A, t0); Object.defineProperty(accessor, "loop", { get() { throw new Error("HOSTILE_SECRET"); } }); invalid([accessor]); const sparse = []; sparse.length = 1; invalid(sparse); invalid(new Proxy([attempt(A, t0)], {})); invalid([{ ...attempt(A, t0), prompt: "HOSTILE_SECRET" }]); invalid([attempt(A, t0)], "anicca_agent_usage", chain([event(A, "2026-08-11T01:00:01.000Z", "success", { prompt: "HOSTILE_SECRET" })])); invalid([attempt(A, t0)], "anicca_agent_usage", emptyChain([event(A, "2026-08-11T01:00:01.000Z")])); invalid([attempt(A, t0)], "anicca_agent_usage", { ...chain([missing(A, "2026-08-11T01:00:01.000Z")]), coverage_exceptions: [] }); const guarded = attempt(A, t0), counter = { value: 0 }, primitive = {}; Object.defineProperty(primitive, Symbol.toPrimitive, { value() { counter.value++; return A; } }); guarded.event_id = primitive; invalid([guarded]); assert.equal(counter.value, 0); });
