"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const crypto = require("node:crypto");
const { readLocalAgentUsageChain } = require("./cfo-local-agent-usage-chain.js");
const { collectAndWriteLocalAgentUsageBatch } = require("./cfo-local-agent-usage-batch-store.js");
const source = "life_manager_agent_usage", at = "2026-08-10T01:02:03Z";
const row = (event_id, loop, task_label, extra = {}) => ({ version: 1, event_id, timestamp: at, loop, task_label, provider: "codex", provider_name: "openai", model: "gpt-5.6", upstream_model: null, attempt: 1, status: "success", measurement: "provider_reported", tokens: { input: 1, cached_input: 0, cache_creation_input: 0, output: 2, reasoning_output: 0, total: 3 }, ...extra });
const lines = (...rows) => Buffer.from(`${rows.map(JSON.stringify).join("\n")}\n`), dir = root => path.join(root, "cfo", "local-agent-usage", source), hash = bytes => crypto.createHash("sha256").update(bytes).digest("hex");
const snapshot = root => fs.readdirSync(dir(root)).sort().map(name => [name, fs.readFileSync(path.join(dir(root), name), "hex"), fs.statSync(path.join(dir(root), name)).mode & 0o777]);
const frozen = value => { assert.ok(Object.isFrozen(value)); if (value && typeof value === "object") Object.values(value).forEach(frozen); };
function publish(root, collectedAt, bytes, prior = null) { return collectAndWriteLocalAgentUsageBatch(root, collectedAt, source, bytes, prior); }
function expectReadFailed(root) { assert.throws(() => readLocalAgentUsageChain(root, source), error => error.message === "cfo_local_agent_usage_chain_invalid:read_failed"); }
function rehash(file, mutate) { const record = JSON.parse(fs.readFileSync(file, "utf8")); mutate(record); const bytes = Buffer.from(JSON.stringify(record)); const target = path.join(path.dirname(file), `${hash(bytes)}.json`); fs.writeFileSync(target, bytes, { mode: 0o600 }); if (target !== file) fs.unlinkSync(file); return target; }

test("missing source and temp remnants are the exact frozen empty result", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-chain-")), root = path.join(parent, "state"); try {
    const expected = { status: "empty", source_state: null, record_count: 0, events: [], counts: { discovered_rows: 0, accepted_rows: 0, duplicate_rows: 0, conflicting_rows: 0, missing_usage_rows: 0, runner_collision_groups: 0, attributed_rows: 0, unattributed_rows: 0 }, coverage_exceptions: [] }, first = readLocalAgentUsageChain(root, source); assert.deepEqual(first, expected); frozen(first); fs.mkdirSync(dir(root), { recursive: true }); fs.writeFileSync(path.join(dir(root), ".abc.tmp"), "HOSTILE_SECRET"); assert.deepEqual(readLocalAgentUsageChain(root, source), expected);
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});

test("orders mixed-offset retry representatives by parsed time and keeps the latest defect", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-chain-")), root = path.join(parent, "state"), bytes = lines(row("f".repeat(24), "life-manager", "life-manager-daily")); try {
    const first = publish(root, at, bytes), state = JSON.parse(fs.readFileSync(path.join(dir(root), `${first.record_id}.json`), "utf8")).source_state, retryEarly = publish(root, "2026-08-10T00:30:00-02:00", bytes, state), retryLate = publish(root, "2026-08-10T01:00:00Z", bytes, state), other = publish(root, "2026-08-10T01:30:00Z", bytes, state);
    rehash(path.join(dir(root), `${retryEarly.record_id}.json`), record => { record.coverage_exceptions = ["source_rewritten"]; }); rehash(path.join(dir(root), `${retryLate.record_id}.json`), record => { record.coverage_exceptions = ["source_rewritten"]; }); rehash(path.join(dir(root), `${other.record_id}.json`), record => { record.coverage_exceptions = ["source_truncated"]; }); assert.deepEqual(readLocalAgentUsageChain(root, source).coverage_exceptions, ["source_truncated"]);
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});

test("an ENOENT during directory listing is a read failure", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-chain-")), root = path.join(parent, "state"), original = fs.readdirSync; try {
    fs.mkdirSync(dir(root), { recursive: true }); fs.readdirSync = () => { const error = new Error("HOSTILE"); error.code = "ENOENT"; throw error; }; expectReadFailed(root);
  } finally { fs.readdirSync = original; fs.rmSync(parent, { recursive: true, force: true }); }
});

test("deduplicates retries, orders linkage, and recomputes immutable coverage", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-chain-")), root = path.join(parent, "state"), rowA = row("a".repeat(24), "life-manager", "life-manager-daily"), rowB = row("b".repeat(24), "connector", "connector-send", { measurement: "unavailable", tokens: { input: null, cached_input: null, cache_creation_input: null, output: null, reasoning_output: null, total: null } }), rowC = row("c".repeat(24), "life-manager", "life-manager-daily"), bytes = lines(rowA, rowB), finalBytes = Buffer.concat([bytes, lines(rowC)]), offsetB = Buffer.byteLength(JSON.stringify(rowA)) + 1, offsetC = bytes.length; try {
    const state = { schema_version: 1, source_id: source, byte_offset: bytes.length, prefix_sha256: hash(bytes), observed_file_size: bytes.length }; publish(root, at, bytes); publish(root, "2026-08-10T02:02:03Z", bytes); publish(root, at, bytes, state); publish(root, at, finalBytes, state); const before = snapshot(root);
    const result = readLocalAgentUsageChain(root, source), expectedEvents = [{ schema_version: 1, source_ledger: "local_agent_usage", source_event_id: `local_agent_usage:${hash(Buffer.from("cfo-local-agent-row-v1\0" + source + "\0" + "0"))}`, runner_event_id: "a".repeat(24), occurred_at: "2026-08-10T01:02:03.000Z", provider: "codex", provider_name: "openai", request_model: "gpt-5.6", upstream_model: null, run: { loop: "life-manager", task_label: "life-manager-daily", attempt: 1, status: "success" }, financial_unit_id: "life_manager_saas", attribution_status: "attributed", measurement: "provider_reported", token_value_basis: "runner_normalized_provider_usage", tokens: { input: 1, cached_input: 0, cache_creation_input: 0, output: 2, reasoning_output: 0, total: 3 }, coverage_status: "covered" }, { schema_version: 1, source_ledger: "local_agent_usage", source_event_id: `local_agent_usage:${hash(Buffer.from("cfo-local-agent-row-v1\0" + source + "\0" + offsetB))}`, runner_event_id: "b".repeat(24), occurred_at: "2026-08-10T01:02:03.000Z", provider: "codex", provider_name: "openai", request_model: "gpt-5.6", upstream_model: null, run: { loop: "connector", task_label: "connector-send", attempt: 1, status: "success" }, financial_unit_id: null, attribution_status: "unattributed", measurement: "unavailable", token_value_basis: "unavailable", tokens: { input: null, cached_input: null, cache_creation_input: null, output: null, reasoning_output: null, total: null }, coverage_status: "missing_usage" }, { schema_version: 1, source_ledger: "local_agent_usage", source_event_id: `local_agent_usage:${hash(Buffer.from("cfo-local-agent-row-v1\0" + source + "\0" + offsetC))}`, runner_event_id: "c".repeat(24), occurred_at: "2026-08-10T01:02:03.000Z", provider: "codex", provider_name: "openai", request_model: "gpt-5.6", upstream_model: null, run: { loop: "life-manager", task_label: "life-manager-daily", attempt: 1, status: "success" }, financial_unit_id: "life_manager_saas", attribution_status: "attributed", measurement: "provider_reported", token_value_basis: "runner_normalized_provider_usage", tokens: { input: 1, cached_input: 0, cache_creation_input: 0, output: 2, reasoning_output: 0, total: 3 }, coverage_status: "covered" }].sort((a, b) => a.source_event_id < b.source_event_id ? -1 : a.source_event_id > b.source_event_id ? 1 : 0); assert.deepEqual(result, { status: "ready", source_state: { schema_version: 1, source_id: source, byte_offset: finalBytes.length, prefix_sha256: hash(finalBytes), observed_file_size: finalBytes.length }, record_count: 3, events: expectedEvents, counts: { discovered_rows: 3, accepted_rows: 3, duplicate_rows: 0, conflicting_rows: 0, missing_usage_rows: 1, runner_collision_groups: 0, attributed_rows: 2, unattributed_rows: 1 }, coverage_exceptions: ["missing_usage", "unattributed_usage"] }); frozen(result); assert.deepEqual(snapshot(root), before);
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});

test("redacts argument, content, schema, chain, and event failures", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-chain-")), root = path.join(parent, "state"), bytes = lines(row("d".repeat(24), "life-manager", "life-manager-daily")); try {
    assert.throws(() => readLocalAgentUsageChain("relative", source), /invalid_state_root$/); assert.throws(() => readLocalAgentUsageChain(root, "HOSTILE_SOURCE"), /invalid_source$/); const receipt = publish(root, at, bytes), file = path.join(dir(root), `${receipt.record_id}.json`); fs.appendFileSync(file, " "); expectReadFailed(root); fs.truncateSync(file, 1); expectReadFailed(root);
    fs.rmSync(dir(root), { recursive: true, force: true }); fs.mkdirSync(dir(root), { recursive: true }); fs.writeFileSync(path.join(dir(root), "unknown.json"), "{}"); expectReadFailed(root);
    fs.rmSync(dir(root), { recursive: true, force: true }); publish(root, at, bytes); const valid = path.join(dir(root), fs.readdirSync(dir(root)).find(name => name.endsWith(".json"))); rehash(valid, record => { record.prior_source_state = { ...record.source_state, byte_offset: record.source_state.byte_offset + 1 }; }); expectReadFailed(root);
    fs.rmSync(dir(root), { recursive: true, force: true }); publish(root, at, bytes); publish(root, "2026-08-10T02:02:03Z", Buffer.concat([bytes, lines(row("e".repeat(24), "life-manager", "life-manager-daily"))])); expectReadFailed(root);
    fs.rmSync(dir(root), { recursive: true, force: true }); const parentReceipt = publish(root, at, bytes), parentPath = path.join(dir(root), `${parentReceipt.record_id}.json`), parentState = JSON.parse(fs.readFileSync(parentPath, "utf8")).source_state, childReceipt = publish(root, at, Buffer.concat([bytes, lines(row("e".repeat(24), "life-manager", "life-manager-daily"))]), parentState), childPath = path.join(dir(root), `${childReceipt.record_id}.json`); rehash(childPath, record => { record.events[0].source_event_id = JSON.parse(fs.readFileSync(parentPath, "utf8")).events[0].source_event_id; }); expectReadFailed(root);
    fs.rmSync(dir(root), { recursive: true, force: true }); const single = publish(root, at, bytes), singleFile = path.join(dir(root), `${single.record_id}.json`); rehash(singleFile, record => { record.events[0].prompt = "HOSTILE_SECRET"; }); expectReadFailed(root);
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});

test("fails closed on physical files, exact nested schemas, gaps, duplicates, and overflow", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-chain-")), root = path.join(parent, "state"), bytes = lines(row("7".repeat(24), "life-manager", "life-manager-daily")), mutate = edit => { fs.rmSync(dir(root), { recursive: true, force: true }); const receipt = publish(root, at, bytes), file = path.join(dir(root), `${receipt.record_id}.json`); edit(file); expectReadFailed(root); }; try {
    mutate(file => fs.chmodSync(file, 0o640)); mutate(file => { const outside = path.join(parent, "outside"); fs.copyFileSync(file, outside); fs.unlinkSync(file); fs.symlinkSync(outside, file); });
    fs.rmSync(dir(root), { recursive: true, force: true }); publish(root, at, bytes); const originalOpen = fs.openSync, originalFstat = fs.fstatSync, originalRead = fs.readSync, opened = [], statted = [], reads = []; fs.openSync = (...args) => { const fd = originalOpen(...args); opened.push(fd); return fd; }; fs.fstatSync = (fd, ...args) => { statted.push(fd); return originalFstat(fd, ...args); }; fs.readSync = (fd, ...args) => { reads.push(fd); return originalRead(fd, ...args); }; try { readLocalAgentUsageChain(root, source); } finally { fs.openSync = originalOpen; fs.fstatSync = originalFstat; fs.readSync = originalRead; } assert.deepEqual(statted, opened); assert.deepEqual(reads, opened); assert.equal(reads.length, 1);
    for (const edit of [record => { record.extra = 1; }, record => { record.source_state.extra = 1; }, record => { record.events[0].run.extra = 1; }, record => { record.events[0].tokens.extra = 1; }]) mutate(file => rehash(file, edit)); mutate(file => rehash(file, record => { record.prior_source_state = { schema_version: 1, source_id: source, byte_offset: 0, prefix_sha256: "0".repeat(64), observed_file_size: 0 }; }));
    fs.rmSync(dir(root), { recursive: true, force: true }); const first = publish(root, at, bytes), firstPath = path.join(dir(root), `${first.record_id}.json`), firstRecord = JSON.parse(fs.readFileSync(firstPath, "utf8")), state = firstRecord.source_state, second = publish(root, at, Buffer.concat([bytes, lines(row("8".repeat(24), "life-manager", "life-manager-daily"))]), state), secondPath = path.join(dir(root), `${second.record_id}.json`); rehash(secondPath, record => { record.events[0] = firstRecord.events[0]; }); expectReadFailed(root);
    fs.rmSync(dir(root), { recursive: true, force: true }); const base = publish(root, at, bytes), basePath = path.join(dir(root), `${base.record_id}.json`), baseState = JSON.parse(fs.readFileSync(basePath, "utf8")).source_state, append = publish(root, at, Buffer.concat([bytes, lines(row("9".repeat(24), "life-manager", "life-manager-daily"))]), baseState); for (const name of fs.readdirSync(dir(root)).filter(name => name.endsWith(".json"))) rehash(path.join(dir(root), name), record => { record.delta_counts.discovered_rows = Number.MAX_SAFE_INTEGER; record.delta_counts.duplicate_rows = Number.MAX_SAFE_INTEGER - 1; }); expectReadFailed(root);
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});

test("keeps cumulative conflicting usage while latest source defects stay current", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-chain-")), root = path.join(parent, "state"), bytes = lines(row("a".repeat(24), "life-manager", "life-manager-daily")); try {
    const first = publish(root, at, bytes), firstPath = path.join(dir(root), `${first.record_id}.json`), firstRecord = JSON.parse(fs.readFileSync(firstPath, "utf8")); rehash(firstPath, record => { record.delta_counts.discovered_rows = 2; record.delta_counts.conflicting_rows = 1; record.coverage_exceptions = ["conflicting_usage"]; }); publish(root, at, Buffer.concat([bytes, lines(row("b".repeat(24), "life-manager", "life-manager-daily"))]), firstRecord.source_state); assert.deepEqual(readLocalAgentUsageChain(root, source).coverage_exceptions, ["conflicting_usage"]);
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});
