"use strict";
const test = require("node:test"); const assert = require("node:assert/strict"); const fs = require("node:fs"); const os = require("node:os"); const path = require("node:path"); const crypto = require("node:crypto");
const { collectAndWriteLocalAgentUsageBatch } = require("./cfo-local-agent-usage-batch-store.js");
const source = "life_manager_agent_usage", at = "2026-08-10T01:02:03Z";
const row = (event_id, extra = {}) => ({ version: 1, event_id, timestamp: at, loop: "gig", task_label: "gig-daily", provider: "codex", provider_name: "openai", model: "gpt-5.6", upstream_model: null, attempt: 1, status: "success", measurement: "provider_reported", tokens: { input: 1, cached_input: 0, cache_creation_input: 0, output: 2, reasoning_output: 0, total: 3 }, ...extra });
const lines = (...rows) => Buffer.from(`${rows.map(JSON.stringify).join("\n")}\n`); const hash = (bytes) => crypto.createHash("sha256").update(bytes).digest("hex"); const mode = (file) => fs.statSync(file).mode & 0o777;
test("publishes immutable content-addressed append batches and converges retries", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-batch-")), root = path.join(parent, "state"); try {
    const firstBytes = lines(row("a".repeat(24), { source_only_raw: { raw_payload: "CFO_RAW_SOURCE_ONLY_SENTINEL", nested: { secret: "CFO_NESTED_SECRET_SENTINEL" } } }), row("b".repeat(24), { loop: "connector", task_label: "connector-send", measurement: "unavailable", tokens: { input: null, cached_input: null, cache_creation_input: null, output: null, reasoning_output: null, total: null } }));
    const first = collectAndWriteLocalAgentUsageBatch(root, at, source, firstBytes, null), dir = path.join(root, "cfo/local-agent-usage", source), firstFile = path.join(dir, `${first.record_id}.json`), firstRecord = fs.readFileSync(firstFile);
    assert.ok(firstBytes.includes("CFO_RAW_SOURCE_ONLY_SENTINEL") && firstBytes.includes("CFO_NESTED_SECRET_SENTINEL")); assert.deepEqual(Object.keys(first), ["record_id", "source_id", "byte_offset", "event_count", "mapping_id"]); assert.ok(Object.isFrozen(first)); assert.equal(hash(firstRecord), first.record_id); assert.equal(mode(firstFile), 0o600); for (const fixed of [path.join(root, "cfo"), path.join(root, "cfo/local-agent-usage"), dir]) assert.equal(mode(fixed), 0o700); const firstJson = JSON.parse(firstRecord); assert.deepEqual(Object.keys(firstJson), ["schema_version", "collected_at", "mapping_id", "prior_source_state", "source_state", "events", "delta_counts", "coverage_exceptions"]); assert.deepEqual(Object.keys(firstJson.events[0]), ["schema_version", "source_ledger", "source_event_id", "runner_event_id", "occurred_at", "provider", "provider_name", "request_model", "upstream_model", "run", "financial_unit_id", "attribution_status", "measurement", "token_value_basis", "tokens", "coverage_status"]); assert.equal(firstJson.events.length, firstJson.delta_counts.accepted_rows); assert.equal(firstJson.source_state.byte_offset, first.byte_offset); assert.ok(["input", "context", "raw_row", "prompt", "response"].every((key) => !Object.hasOwn(firstJson, key))); assert.doesNotMatch(firstRecord.toString(), /CFO_RAW_SOURCE_ONLY_SENTINEL|CFO_NESTED_SECRET_SENTINEL|source_only_raw|raw_payload/);
    const allBytes = Buffer.concat([firstBytes, lines(row("c".repeat(24)))]), second = collectAndWriteLocalAgentUsageBatch(root, at, source, allBytes, JSON.parse(firstRecord).source_state), secondPath = path.join(dir, `${second.record_id}.json`), secondBefore = fs.readFileSync(secondPath); assert.notEqual(second.record_id, first.record_id); assert.deepEqual(JSON.parse(secondBefore).prior_source_state, JSON.parse(firstRecord).source_state); assert.equal(second.event_count, 1); assert.deepEqual(collectAndWriteLocalAgentUsageBatch(root, at, source, allBytes, JSON.parse(firstRecord).source_state), second); assert.deepEqual(fs.readdirSync(dir).filter((name) => name.endsWith(".json")).sort(), [path.basename(firstFile), path.basename(secondPath)].sort());
    assert.equal(mode(secondPath), 0o600);
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});
test("does not publish on file-fsync failure and keeps post-rename receipt byte-identical on retry", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-batch-")), root = path.join(parent, "state"), bytes = lines(row("d".repeat(24))); try {
    const stable = collectAndWriteLocalAgentUsageBatch(root, at, source, bytes, null), dir = path.join(root, "cfo/local-agent-usage", source), stablePath = path.join(dir, `${stable.record_id}.json`), stableBefore = fs.readFileSync(stablePath), prior = JSON.parse(stableBefore).source_state, nextBytes = Buffer.concat([bytes, lines(row("e".repeat(24)))]); assert.throws(() => collectAndWriteLocalAgentUsageBatch(root, at, source, nextBytes, prior, { fsyncImpl() { throw Error("HOSTILE"); } }), /cfo_local_agent_usage_batch_store_invalid:write_failed$/); assert.deepEqual(fs.readFileSync(stablePath), stableBefore); assert.deepEqual(fs.readdirSync(dir).filter((name) => name.endsWith(".json")), [path.basename(stablePath)]); assert.equal(fs.readdirSync(dir).filter((name) => name.endsWith(".tmp")).length, 0);
    let failDirectory = true; const fsyncImpl = (fd) => { if (fs.fstatSync(fd).isDirectory() && failDirectory) { failDirectory = false; throw Error("HOSTILE"); } fs.fsyncSync(fd); }; const failed = () => collectAndWriteLocalAgentUsageBatch(root, at, source, nextBytes, prior, { fsyncImpl }); assert.throws(failed, /cfo_local_agent_usage_batch_store_invalid:write_failed$/); const published = fs.readdirSync(dir).filter((name) => name.endsWith(".json")); assert.equal(published.length, 2); const newName = published.find((name) => name !== path.basename(stablePath)); assert.ok(newName); const newPath = path.join(dir, newName), newBefore = fs.readFileSync(newPath); assert.equal(hash(newBefore), newName.slice(0, -5)); assert.equal(mode(newPath), 0o600); assert.deepEqual(fs.readFileSync(stablePath), stableBefore); const retry = collectAndWriteLocalAgentUsageBatch(root, at, source, nextBytes, prior); assert.equal(retry.record_id, newName.slice(0, -5)); assert.deepEqual(fs.readFileSync(newPath), newBefore); assert.deepEqual(fs.readdirSync(dir).filter((name) => name.endsWith(".json")).sort(), [path.basename(stablePath), newName].sort());
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});
test("rejects store inputs before collector and directory mutation", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "cfo-batch-")); try {
    const hostile = ["HOSTILE_SOURCE", "HOSTILE_BYTES", "HOSTILE_STATE"], storeCases = [[`${parent}/nested/../invalid-state-root`, at, ...hostile], [path.join(parent, "invalid-collected-at"), "bad", ...hostile], [path.join(parent, "invalid-options"), at, ...hostile, { extra: "HOSTILE_OPTIONS" }]], messages = ["cfo_local_agent_usage_batch_store_invalid:invalid_state_root", "cfo_local_agent_usage_batch_store_invalid:invalid_collected_at", "cfo_local_agent_usage_batch_store_invalid:invalid_options"];
    for (let index = 0; index < storeCases.length; index += 1) { const args = storeCases[index], target = args[0].replace(`${parent}/nested/../`, `${parent}/`); assert.throws(() => collectAndWriteLocalAgentUsageBatch(...args), (error) => error.message === messages[index] && !/HOSTILE/.test(error.message)); assert.equal(fs.existsSync(target), false); assert.equal(fs.existsSync(path.join(target, "cfo")), false); }
    const collectorRoot = path.join(parent, "collector"), collectorCases = [[[collectorRoot, at, "HOSTILE_SOURCE", Buffer.alloc(0), null], "cfo_local_agent_usage_cursor_invalid:invalid_source"], [[collectorRoot, at, source, "HOSTILE_BYTES", null], "cfo_local_agent_usage_cursor_invalid:invalid_bytes"]]; for (const [args, message] of collectorCases) { assert.throws(() => collectAndWriteLocalAgentUsageBatch(...args), (error) => error.message === message && !/HOSTILE/.test(error.message)); assert.equal(fs.existsSync(collectorRoot), false); }
  } finally { fs.rmSync(parent, { recursive: true, force: true }); }
});
