#!/usr/bin/env bash
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# capafy-loop-cli.sh — always-on Capafy money-loop claude-p session (copied from earn/clip). Detached tmux
# runs headless claude that registers a DAILY driver cron then idles; healthcheck restarts if dead/stale.
set -uo pipefail
SOCK="/tmp/anicca-capafy-loop-tmux.sock"; SESSION="anicca-capafy-loop"
CLAUDE="$(command -v claude || echo /opt/homebrew/bin/claude)"
STARTUP='You are the Anicca Capafy money-loop core (claude-p, self-improving + self-healing; money → Dais bank; human + main-agent NOT in this loop). FIRST call CronList; if no job whose prompt mentions capafy money loop exists, CronCreate cron="0 9 * * *" recurring=true durable=true prompt="ONE pass of the Capafy money loop. STEP0 SELF-HEAL: if ~/.openclaw/state/capafy-loop-selfheal-request.json exists, read it, diagnose, fix yourself: CAPAFY-AUTH-DOWN → re-login via ~/.openclaw/skills/capafy-autopublish (login-init → read OTP from redacted@example.invalid via gog gmail → login-verify → copy token into vendor/capafy-publisher/config.json); CAPAFY-LOOP-STALE/NEVER-RAN → run bash ~/.openclaw/skills/capafy-autopublish/scripts/daily_loop.sh; verify heal clears then rm the json; if unfixable invoke self/issue-dev then rm it. STEP1 MEASURE: bash ~/anicca/skills/self/capafy-loop/loop.sh and read its STATE.md. STEP2 ACT (single highest-EV move toward real Capafy revenue; your judgment, no script): revenue is \$0 and the wall is our listings are not competitive/discoverable (top sellers DO sell) — so improve SUPPLY QUALITY: use the capafy-autopublish market-search to read a CURRENT top seller, clone its pricing/structure/category into ONE new sandbox-complete listing (honest, no overclaim, lint-clean) and publish it via bash ~/.openclaw/skills/capafy-autopublish/scripts/daily_loop.sh; OR retire a dead listing to free a slot. Do ONE. STEP3 VERIFY: only a real subscriber or a listing reaching status=4 counts — published alone is NOT revenue; record the observable in STATE.md. STEP4 REPORT: bash ~/anicca/skills/report/loop-report.sh capafy \"<what you did + real metric>\" <success|failure|no-op> <usd or 0> \"<evidence url or none>\". FINALLY touch ~/.openclaw/state/.capafy-loop-last-pass. Blocker is not stop.". THEN run ONE pass now (same body). THEN stop and idle.'
status(){ tmux -S "$SOCK" has-session -t "$SESSION" 2>/dev/null && echo ALIVE || echo DEAD; }
case "${1:-}" in --status) status; exit 0;; --restart) tmux -S "$SOCK" kill-session -t "$SESSION" 2>/dev/null||true;; esac
if [ "${1:-}" != "--restart" ] && tmux -S "$SOCK" has-session -t "$SESSION" 2>/dev/null; then echo "capafy-loop already ALIVE"; exit 0; fi
tmux -S "$SOCK" new-session -d -s "$SESSION" "$CLAUDE" --name "$SESSION" --model sonnet --dangerously-skip-permissions --add-dir "$HOME" -- "$STARTUP"
mkdir -p "$HOME/.openclaw/state" && touch "$HOME/.openclaw/state/.capafy-loop-last-start"; sleep 2
echo "capafy-loop started ($(status))."
