#!/usr/bin/env bash
# bill_drafter.sh — queue file pattern matching apply-to-funder.
# Writes a K-Dense scientific-writing request file. The cron runner picks
# it up on next agentTurn, reads ~/.openclaw/skills/scientific-writing/SKILL.md,
# generates section text, and writes the result back per-section.
set -euo pipefail

bill_drafter_queue() {
  local pillar="$1" title="$2" target_words="${3:-1500}"
  local ts; ts="$(date -u +%Y%m%d-%H%M%S)"
  local out_dir="$SKILL/data/drafts/bills"
  mkdir -p "$out_dir"
  local kfile="$out_dir/${ts}.kdense.md"
  cat > "$kfile" <<EOF
# K-Dense scientific-writing draft request — pillar ${pillar}
# generated by politician/lib/bill_drafter.sh
# fewshot corpus: see ~/.openclaw/skills/politician/data/bill_corpus/README.md
# target language: en
# target chamber: US Senate / US House (dual draft)

## title

${title}

## section / findings_and_purpose  ←  invoke skill: scientific-writing
target_words: 250
language: en
fewshot:
  - data/bill_corpus/README.md (sections: SB-1047, SB-53, EU-AI-Act)
prompt: |
  Draft the "Findings and Purpose" section of a model bill on pillar ${pillar}.
  Use Ramseyer-style legislative format. Cite empirical work where available.

## section / definitions  ←  invoke skill: scientific-writing
target_words: 200
language: en
prompt: |
  Define terms used in this bill. Where possible, align definitions with NIST
  AI RMF and EU AI Act (the latter for international reference, not adoption).

## section / operative_provisions  ←  invoke skill: scientific-writing
target_words: ${target_words}
language: en
prompt: |
  Draft the operative sections (numbered §§) for pillar ${pillar}. Include
  enforcement mechanism, agency or court of competent jurisdiction, and
  effective date. Maintain Ramseyer style throughout.

## section / red_line_vs_existing_us_code  ←  invoke skill: scientific-writing
target_words: 300
language: en
prompt: |
  Identify each existing US Code section the bill amends or supersedes.
  Present as red-line: stricken text + new text. If creating new chapter,
  cite the placement (e.g., 5 U.S.C. ch. 24).

> Agent must read ~/.openclaw/skills/scientific-writing/SKILL.md and follow
> its IMRAD/citation conventions to produce each section.
EOF
  echo "$kfile"
}

bill_drafter_status() {
  # Print queued files awaiting K-Dense fulfilment.
  local out_dir="$SKILL/data/drafts/bills"
  if [[ ! -d "$out_dir" ]]; then echo "0 queued"; return; fi
  local n; n=$(find "$out_dir" -name "*.kdense.md" 2>/dev/null | wc -l | tr -d ' ')
  echo "$n queued"
}
