#!/usr/bin/env python3
# instagrapi-based IG Reel poster — the VERIFIED FREE posting method (2026-07-14), replaces the
# web-composer post_reel.py which was a structural dead end (IG silently drops automated web posts).
# Flow: pull the CloakBrowser's already-logged-in sessionid (avoids a fresh-login challenge) ->
# instagrapi.login_by_sessionid -> ffmpeg thumbnail (avoids moviepy dep) -> clip_upload ->
# verify the reel is publicly visible. Prints ONE structured JSON line matching run.sh's contract
# ({"outcome": "published"|"failed"|"dry", "post_url": ..., "before_hrefs": []}).
#
# ★ SESSION POLICY (SSOT: docs/earn/ig-4account-reels-carousel-loop-plan.md v22/v23/v24) ★
# v23's core finding: the FIRST login after signup ("golden session") passes cleanly. Once that
# session dies, a password relogin ALWAYS trips bloks ChallengeRequired and semi-poisons the
# account. So the only thing that matters is: never let the golden session die, and never relogin
# once it has. Concretely (copy-sourced from alsk1992/instagram-ai-agent + subzeroid/instagrapi,
# v24):
#   1. tier1 (gold standard) = load_settings() + a read-only verification call. NEVER falls
#      through to password login while a saved session exists — even if it looks dead, a plain
#      LoginRequired is not a green light to relogin (only a genuinely fresh account, with NO
#      settings file at all, is allowed to take the tier3 path). copy=ig.py L556-708.
#   2. tier2 (browser sessionid) is skipped entirely for accounts with session_owner=="instagrapi"
#      in clip-accounts.json (v22: a parallel browser session is what kills the golden session via
#      churn in the first place).
#   3. tier3 (password login) fires ONLY when instagrapi-<handle>.json has never existed, gated by
#      a 24h cooldown stamp, and never generates a second attempt.
#   4. A bloks ChallengeRequired at ANY tier means the account is poisoned. We do not retry login —
#      mark_poisoned() flips clip-accounts.json status to poisoned_manual_backup and self-heal is
#      expected to provision a replacement account. copy=auth.py L779-786.
#   5. Device uuids are never freshly generated by this module — the only path that sets them is
#      load_settings()->set_settings()->init(), which restores the uuids already saved in the
#      settings file. We never call cl.set_uuids() with newly generated values.
import argparse, json, os, sys, re, time, subprocess, urllib.request
sys.path.insert(0, os.path.expanduser("~/.claude/skills/ig-account-create/scripts"))
import cdp  # noqa: E402
from websocket import create_connection  # noqa: E402
from instagrapi.exceptions import ChallengeRequired, LoginRequired  # noqa: E402

C = os.path.expanduser


def make_gmail_handler(handle):
    # instagrapi calls this on an email challenge; auto-read the 6-digit code from the
    # account's gmail plus-address inbox via `gog gmail`. Never prints the code.
    def handler(username=None, choice=None):
        creds = json.load(open(C(f"~/.cloak/ig-{handle}.json")))
        base = creds["email"].split("+")[0] + "@gmail.com"
        end = time.time() + 180
        while time.time() < end:
            out = subprocess.run(
                ["gog", "gmail", "search", "from:instagram newer_than:1h", "-j",
                 "--results-only", "-a", base],
                capture_output=True, text=True)
            try:
                threads = json.loads(out.stdout) or []
            except Exception:
                threads = []
            for t in threads:
                body = subprocess.run(
                    ["gog", "gmail", "get", t.get("id"), "-j", "--results-only", "-a", base],
                    capture_output=True, text=True).stdout
                g = re.search(r"(?<!\d)(\d{6})(?!\d)", t.get("subject", "") + " " + body)
                if g:
                    return g.group(1)
            time.sleep(10)
        raise Exception("no gmail challenge code within 180s")
    return handler


def logout_reason(cl):
    # Diagnostic ONLY — never raises. When IG kills a session it may set last_response's
    # `logout_reason` to signature_revoked / password_changed / concurrent_session; capturing it is
    # the single cheapest way to confirm WHY a session died (per instagrapi.com/guides/errors/
    # login-required). Read-only: does not touch the login flow. Returns "" when unavailable.
    try:
        lr = cl.last_response.json()
        return lr.get("logout_reason") or lr.get("message") or ""
    except Exception:
        return ""


def is_bloks_challenge(e):
    # v23/v24: a bloks native ChallengeRequired means the account is poisoned — relogin can never
    # recover it. This is the ONLY signal that should trigger mark_poisoned() (a plain
    # LoginRequired/TooManyRedirects is just "session dead", handled by refusing to relogin).
    return isinstance(e, ChallengeRequired)


def account_session_owner(handle, accounts_path=None):
    # v22: some accounts are flagged session_owner="instagrapi" — a parallel browser session
    # (tier2) is what causes session churn on those accounts, so tier2 must be skipped for them.
    accounts_path = accounts_path or C("~/.cloak/clip-accounts.json")
    try:
        accounts = json.load(open(accounts_path))
    except Exception:
        return None
    for a in accounts:
        if a.get("handle") == handle:
            return a.get("session_owner")
    return None


def mark_poisoned(handle, reason, accounts_path=None):
    # v23/v24: bloks ChallengeRequired = the account is poisoned. Flip clip-accounts.json's status
    # so self-heal picks it up and provisions a replacement — do NOT retry login on this account.
    accounts_path = accounts_path or C("~/.cloak/clip-accounts.json")
    try:
        accounts = json.load(open(accounts_path))
    except Exception:
        return False
    changed = False
    for a in accounts:
        if a.get("handle") == handle:
            a["status"] = "poisoned_manual_backup"
            a["poisoned_reason"] = reason
            a["poisoned_at"] = time.strftime("%Y-%m-%dT%H:%MZ", time.gmtime())
            changed = True
    if changed:
        with open(accounts_path, "w") as f:
            json.dump(accounts, f, indent=2, ensure_ascii=False)
    return changed


def keepalive(cl):
    # Read-only session-alive probe (v24 point 2). Never writes, never relogins. Returns False
    # ONLY on a confirmed LoginRequired (the session is actually dead); any other exception is
    # treated as an inconclusive/transient blip, not proof of death, so it must NOT trigger a
    # relogin attempt elsewhere in the pipeline.
    try:
        cl.get_timeline_feed()
        return True
    except LoginRequired:
        return False
    except Exception:
        return True


def gentle_ping(cl):
    # Second, even-lighter keepalive probe: instagrapi's own launcher/sync/ private endpoint — the
    # same idle-refresh call the real IG app fires on cold start — used by long-lived-session IG
    # bots to keep server-side trust warm without a full feed read.
    # copy=alsk1992/instagram-ai-agent plugins/ig.py L1142-1250 (two-stage keepalive: feed probe +
    # launcher/sync ping). instagrapi exposes the same endpoint as Client.sync_launcher(); if a
    # future instagrapi version drops it, fall back to keepalive()'s get_timeline_feed read.
    try:
        cl.sync_launcher(login=False)
        return True
    except LoginRequired:
        return False
    except AttributeError:
        return keepalive(cl)
    except Exception:
        return True


def login_resilient(cl, handle, port, res, settings_path=None, accounts_path=None):
    # Self-healing login so the loop never needs a human to log in again. Order matters (v22/v23/
    # v24 — see module docstring):
    #   1) reuse the saved instagrapi session (device+cookies) — the "golden session". NEVER falls
    #      through to password login while this tier is available.
    #   2) fall back to the browser's live sessionid — but ONLY for accounts NOT owned by
    #      instagrapi (session_owner flag), since a parallel browser session is the churn vector.
    #   3) fall back to a full password login — but ONLY for an account that has NEVER had a saved
    #      instagrapi session (settings file truly absent). One attempt, 24h cooldown.
    settings = settings_path or C(f"~/.cloak/instagrapi-{handle}.json")
    settings_existed = os.path.exists(settings)

    if settings_existed:
        try:
            cl.load_settings(settings)
            cl.get_timeline_feed()  # validates the session; identity guaranteed by filename
            return True
        except Exception as e:
            reason = logout_reason(cl)
            res["tier1_dead"] = f"{type(e).__name__}: {reason}"
            print(f"login_resilient tier1 (saved session) dead: {type(e).__name__} logout_reason={reason!r}", file=sys.stderr)
            if is_bloks_challenge(e):
                mark_poisoned(handle, f"tier1 load_settings ChallengeRequired: {reason}", accounts_path)
                res["poisoned"] = True
                res["error"] = "account poisoned (bloks ChallengeRequired) on tier1 — self-heal must replace it, not relogin"
                return False

    if account_session_owner(handle, accounts_path) != "instagrapi":
        try:
            _, sid = get_sessionid(port)
            if sid:
                cl.login_by_sessionid(sid)
                if cl.username == handle:
                    cl.dump_settings(settings)
                    return True
        except Exception as e:
            reason = logout_reason(cl)
            res["tier2_dead"] = f"{type(e).__name__}: {reason}"
            print(f"login_resilient tier2 (browser sessionid) dead: {type(e).__name__} logout_reason={reason!r}", file=sys.stderr)
            if is_bloks_challenge(e):
                mark_poisoned(handle, f"tier2 login_by_sessionid ChallengeRequired: {reason}", accounts_path)
                res["poisoned"] = True
                res["error"] = "account poisoned (bloks ChallengeRequired) on tier2 — self-heal must replace it, not relogin"
                return False
    else:
        res["tier2_skipped"] = "session_owner=instagrapi — browser session forbidden for this account (v22 churn guard)"

    if settings_existed:
        # ★ RELOGIN REFUSAL (v23 core finding): a saved session that died is NOT a green light to
        # password-login. Relogin on a previously-alive session is exactly what trips bloks and
        # semi-poisons the account. Refuse and let self-heal replace the account instead. ★
        res["error"] = "saved session dead and no fresh-account exemption applies — refusing relogin (v23 bloks trap). self-heal must replace this account."
        return False

    try:
        # ★ TIER3 COOLDOWN GUARD (TASKLIST 3a): repeated password logins are a STOP signal to IG —
        # each attempt deepens distrust and triggers session revocation / reCAPTCHA Enterprise.
        # Observed 2026-07-16: two tier3 logins within minutes both "succeeded" then got revoked
        # mid-use (LoginRequired during clip_upload). At most ONE password attempt per 24h, and
        # only for an account that has never had a saved session (settings_existed is False here).
        stamp = C(f"~/.cloak/.last-pwlogin-{handle}")
        last = os.path.getmtime(stamp) if os.path.exists(stamp) else 0
        if time.time() - last < 24 * 3600:
            res["error"] = "tier3 password login on 24h cooldown — refusing to hammer IG login (3a)"
            return False
        open(stamp, "w").write(str(int(time.time())))  # stamp BEFORE the attempt: failures count too
        creds = json.load(open(C(f"~/.cloak/ig-{handle}.json")))
        cl.login(creds["username"], creds["pw"])
        cl.dump_settings(settings)
        return True
    except Exception as e:
        reason = logout_reason(cl)
        if is_bloks_challenge(e):
            mark_poisoned(handle, f"tier3 login ChallengeRequired: {reason}", accounts_path)
            res["poisoned"] = True
            res["error"] = "account poisoned (bloks ChallengeRequired) on first-ever login — self-heal must provision a replacement"
            return False
        res["error"] = f"all login paths failed: {type(e).__name__}: {str(e)[:200]}"
        return False


def get_sessionid(port):
    tabs = json.load(urllib.request.urlopen(f"http://localhost:{port}/json/list"))
    tid = next(t["id"] for t in tabs if t.get("type") == "page" and "instagram.com" in (t.get("url") or ""))
    ws = create_connection(cdp.page_ws(tid), timeout=20, suppress_origin=True, max_size=None)
    ws.send(json.dumps({"id": 1, "method": "Network.enable"}))
    ws.send(json.dumps({"id": 2, "method": "Network.getAllCookies"}))
    sid = None
    end = time.time() + 15
    while time.time() < end:
        m = json.loads(ws.recv())
        if m.get("id") == 2:
            for c in m["result"]["cookies"]:
                if c["name"] == "sessionid" and "instagram" in c["domain"]:
                    sid = c["value"]
            break
    ws.close()
    return tid, sid


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--video", required=True)
    ap.add_argument("--caption-file", required=True)
    ap.add_argument("--handle", required=True)
    ap.add_argument("--port", default=os.environ.get("CDP_PORT", "9222"))
    ap.add_argument("--live", action="store_true")
    a = ap.parse_args()
    res = {"handle": a.handle, "outcome": "failed", "post_url": None, "before_hrefs": []}
    try:
        caption = open(a.caption_file, encoding="utf-8").read().strip()

        from instagrapi import Client
        cl = Client()
        cl.delay_range = [2, 5]
        cl.challenge_code_handler = make_gmail_handler(a.handle)
        # ★ ACCOUNT GUARD (fail-closed): the session is loaded from instagrapi-<handle>.json (tier 1/3)
        #   or verified cl.username==handle (tier 2), so we can only ever act as the right account. ★
        if not login_resilient(cl, a.handle, a.port, res):
            print(json.dumps(res, ensure_ascii=False)); return

        if not a.live:
            res["outcome"] = "dry"; res["reached"] = "login-ok"
            print(json.dumps(res, ensure_ascii=False)); return

        thumb = a.video + ".jpg"
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", a.video, "-ss", "1", "-vframes", "1", thumb], check=True)
        media = cl.clip_upload(a.video, caption, thumbnail=thumb)
        d = media.model_dump() if hasattr(media, "model_dump") else media.dict()
        code = d.get("code")
        url = f"https://www.instagram.com/reel/{code}/"

        # REALITY GATE: confirm the reel is publicly visible (logged-out) before claiming success.
        public = None
        time.sleep(3)
        try:
            req = urllib.request.Request(f"https://www.instagram.com/{a.handle}/", headers={"User-Agent": "Mozilla/5.0"})
            html = urllib.request.urlopen(req, timeout=12).read().decode("utf-8", "ignore")
            public = bool(code) and code in html
        except Exception:
            public = None  # network gate; instagrapi's returned code is still the source of truth

        res["outcome"] = "published"; res["post_url"] = url; res["code"] = code
        res["public_verified"] = public; res["reached"] = "PUBLISHED"
    except Exception as e:
        res["error"] = f"{type(e).__name__}: {str(e)[:300]}"
    print(json.dumps(res, ensure_ascii=False))


if __name__ == "__main__":
    main()
