plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/anicca/anicca/.worktrees/capafy-skills-landing/skills/earn/capafy-marketing/site"
publishOrigin = "default"
base = "/Users/anicca/anicca/.worktrees/capafy-skills-landing/skills/earn/capafy-marketing/site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]