"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),test=require("node:test");
const {buildFunderSubmissionReceipt}=require("./funder-submission-receipt.js");
const {appendFunderSubmissionReceipt}=require("./funder-submission-receipt-store.js");
const {buildFunderSubmissionMessage,deliverFunderSubmissionMessage}=require("./funder-submission-telegram.js");
const SQL=fs.readFileSync(path.join(__dirname,"../migrations/2026-08-02-lm-funder-submission-ledger.sql"),"utf8");
function valid(){return {tenantId:"dais-local",funderId:"yc-fall-2026",draftId:"0b61fe42-e383-490d-b60e-04f1ad7ec5df",applicationUrl:"https://apply.ycombinator.com/home",home:{status:"in_review",observedAt:"2026-08-01T17:32:00Z"},mail:{messageId:"19fbe6135cf98bd4",threadId:"19fbe6135cf98bd4",internalDateMs:1785605465000,from:"apply@ycombinator.com",subject:"YC Fall 2026 Application Submitted",body:"Your application to the Fall 2026 batch for Anicca has been submitted.",dkimPass:true,spfPass:true,dmarcPass:true}}}
test("exact YC home and authenticated confirmation mail produce one receipt",()=>{const r=buildFunderSubmissionReceipt(valid());assert.equal(r.status,"submitted");assert.equal(r.provider_status,"in_review");assert.match(r.ledger_id,/^funder-ledger:[0-9a-f]{64}$/);assert.equal(r.mail_message_id,r.mail_thread_id)});
test("spoof, mismatch, bad status, and invalid timing fail closed",()=>{for(const x of [{mail:{...valid().mail,from:"attacker.test"}},{mail:{...valid().mail,subject:"Other"}},{home:{...valid().home,status:"draft"}},{home:{...valid().home,observedAt:"2026-08-01T17:30:00Z"}},{draftId:"bad"}])assert.throws(()=>buildFunderSubmissionReceipt({...valid(),...x}),/submission receipt/i)});
test("migration and store are tenant-bound append-only exact replay",async()=>{assert.match(SQL,/CREATE TABLE IF NOT EXISTS public\.lm_funder_submission_ledger/i);assert.match(SQL,/ENABLE ROW LEVEL SECURITY/i);assert.doesNotMatch(SQL,/UPDATE public\.lm_funder_submission_ledger/i);const r=buildFunderSubmissionReceipt(valid()),calls=[];const saved=await appendFunderSubmissionReceipt(r,{query:async(sql,params)=>(calls.push({sql,params}),{rows:[{ledger_id:params[1],inserted:true}]})});assert.equal(saved.ledger_id,r.ledger_id);assert.match(calls[0].sql,/ON CONFLICT DO NOTHING/i);assert.doesNotMatch(calls[0].sql,/UPDATE/i)});
test("Telegram is one Japanese message and requires positive provider ID",async()=>{const receipt=buildFunderSubmissionReceipt(valid());assert.match(buildFunderSubmissionMessage(receipt),/YC Fall 2026へ提出完了/);let calls=0;const d=await deliverFunderSubmissionMessage({tenantId:"dais-local",telegramTarget:"dais",receipt},{send:async()=>{calls++;return 'message_id: 7001'},observedAt:()=>"2026-08-01T17:33:00Z"});assert.equal(calls,1);assert.equal(d.provider_id,"7001");await assert.rejects(()=>deliverFunderSubmissionMessage({tenantId:"dais-local",telegramTarget:"dais",receipt},{send:async()=>"ok"}),/positive message ID/i)});
