"use strict";
const assert=require("node:assert/strict");
const {createHash,randomUUID}=require("node:crypto");
const fs=require("node:fs");const path=require("node:path");const test=require("node:test");
const {buildFunderAssetFreshnessGate}=require("./funder-asset-freshness.js");
const {appendFunderAssetFreshnessGate}=require("./funder-asset-freshness-store.js");
const SQL=fs.readFileSync(path.join(__dirname,"../migrations/2026-08-02-lm-funder-asset-freshness.sql"),"utf8");
const sha=x=>createHash("sha256").update(x).digest("hex");
function fixture(){
 const kit="# Company\nAnicca is autonomous.\n",traction="# Traction\nMRR uses the live ledger.\n",deckSource="MRR {{dashboard:mrr.total_usd}}";
 const dashboard=JSON.stringify({updated_at:"2026-08-02T02:00:00.000Z",mrr:{total_usd:42,sources:{stripe:15,revenuecat_mobile:27}},views:{weekly_total:3540},meta:{fetcher_versions:{stripe:"2026-08-02T01:30:00.000Z",rc:"2026-08-02T01:31:00.000Z",postiz:"2026-08-02T01:32:00.000Z"}}});
 const pdf=Buffer.from("%PDF-current-deck"),video=Buffer.from("current-founder-video");
 return {tenantId:"dais-local",attemptId:randomUUID(),funderId:"spc-f26",evaluatedAt:"2026-08-02T03:00:00.000Z",
  kitSnapshot:{captured_at:"2026-08-02T02:40:00.000Z",kit_digest:sha(`${kit}\0${traction}\0${deckSource}`),documents:[{ref:"application-kit://KIT.md",content:kit,sha256:sha(kit),modified_at:"2026-07-17T09:50:49.000Z"},{ref:"application-kit://answers/q04_traction.en.md",content:traction,sha256:sha(traction),modified_at:"2026-07-17T09:50:49.000Z"},{ref:"application-kit://deck/deck-en.md",content:deckSource,sha256:sha(deckSource),modified_at:"2026-08-02T01:50:00.000Z"}]},
  dashboardSnapshot:{url:"https://aniccaai.com/dashboard.json",fetched_at:"2026-08-02T02:35:00.000Z",content:dashboard,sha256:sha(dashboard)},
  assessment:{company_facts:[{claim_id:"company-autonomy",source_ref:"application-kit://KIT.md",evidence_excerpt:"Anicca is autonomous."}],traction:[{claim_id:"weekly-views",dashboard_pointer:"views.weekly_total",provider_timestamp_pointer:"meta.fetcher_versions.postiz",reported_value:3540,source_ref:"application-kit://answers/q04_traction.en.md",evidence_excerpt:"MRR uses the live ledger."}],mrr:{total_pointer:"mrr.total_usd",reported_value:42,recurring_revenue_pointers:["mrr.sources.stripe","mrr.sources.revenuecat_mobile"],provider_timestamp_pointers:["meta.fetcher_versions.stripe","meta.fetcher_versions.rc"],rationale:"Stripe subscriptions plus RevenueCat mobile subscriptions."}},
  assets:[{kind:"deck",ref:"application-kit://deck/deck-en.pdf",bytes:pdf,sha256:sha(pdf),captured_at:"2026-08-02T02:45:00.000Z",modified_at:"2026-08-02T02:10:00.000Z",source_ref:"application-kit://deck/deck-en.md",source_sha256:sha(deckSource),mime:"application/pdf",pages:9,size_bytes:pdf.length},{kind:"video",ref:"application-kit://videos/yc-founder-video-2026-fall.mp4",bytes:video,sha256:sha(video),captured_at:"2026-08-02T02:46:00.000Z",modified_at:"2026-07-30T02:00:00.000Z",mime:"video/mp4",duration_seconds:57.84,size_bytes:video.length,video_codec:"h264",audio_codec:"aac",width:720,height:1280}]};
}
test("current claims, exact MRR arithmetic, deck lineage, and selected video allow submit",()=>{const gate=buildFunderAssetFreshnessGate(fixture());assert.equal(gate.decision,"allow");assert.equal(gate.submit_allowed,true);assert.match(gate.gate_id,/^funder-freshness-gate:[0-9a-f]{64}$/);assert.equal(JSON.stringify(gate).includes("Anicca is autonomous"),false);assert.equal(gate.asset_receipts.length,2);assert.equal(gate.claim_receipts.length,2);});
test("stale dashboard/provider, arithmetic drift, fabricated citation, and old deck fail closed",()=>{const cases=[x=>{x.dashboardSnapshot.fetched_at="2026-08-01T00:00:00Z";},x=>{const d=JSON.parse(x.dashboardSnapshot.content);d.updated_at="2026-07-01T00:00:00Z";x.dashboardSnapshot.content=JSON.stringify(d);x.dashboardSnapshot.sha256=sha(x.dashboardSnapshot.content);},x=>{const d=JSON.parse(x.dashboardSnapshot.content);d.meta.fetcher_versions.rc="2026-07-01T00:00:00Z";x.dashboardSnapshot.content=JSON.stringify(d);x.dashboardSnapshot.sha256=sha(x.dashboardSnapshot.content);},x=>{x.assessment.mrr.reported_value=99;},x=>{x.assessment.company_facts[0].evidence_excerpt="invented";},x=>{x.assets[0].modified_at="2026-08-01T00:00:00Z";}];for(const mutate of cases){const x=fixture();mutate(x);const gate=buildFunderAssetFreshnessGate(x);assert.equal(gate.submit_allowed,false);assert.equal(gate.decision,"refresh_required");}});
test("missing digest, oversized/long/wrong-codec video, and unbound deck source are rejected",()=>{for(const mutate of [x=>{x.assets[1].sha256="0".repeat(64);},x=>{x.assets[1].duration_seconds=60.01;},x=>{x.assets[1].size_bytes=100*1024*1024+1;},x=>{x.assets[1].video_codec="vp9";},x=>{x.assets[0].source_sha256="f".repeat(64);}]){const x=fixture();mutate(x);assert.throws(()=>buildFunderAssetFreshnessGate(x),/freshness/i);}});
test("ledger is append-only, RLS-protected, tenant/attempt-bound, and exact replay only",async()=>{assert.match(SQL,/CREATE TABLE IF NOT EXISTS public\.lm_funder_asset_freshness_gates/i);assert.match(SQL,/ENABLE ROW LEVEL SECURITY/i);assert.match(SQL,/REVOKE ALL .* FROM PUBLIC/i);assert.doesNotMatch(SQL,/UPDATE public\./i);const gate=buildFunderAssetFreshnessGate(fixture()),calls=[];const saved=await appendFunderAssetFreshnessGate(gate,{query:async(sql,params)=>{calls.push({sql,params});return{rows:[{gate_id:params[2]}]};}});assert.equal(saved.inserted,true);assert.match(calls[0].sql,/ON CONFLICT .* DO NOTHING/i);await assert.rejects(()=>appendFunderAssetFreshnessGate(gate,{query:async()=>({rows:[]})}),/collision/i);});
