"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),test=require("node:test"),{createHash,randomUUID}=require("node:crypto");
const {collectFunderAssetFreshnessGate,validateFunderAssetFreshnessGate,verifyFunderSubmissionBinding}=require("./funder-asset-freshness.js"),{appendFunderAssetFreshnessGate}=require("./funder-asset-freshness-store.js");
const SQL=fs.readFileSync(path.join(__dirname,"../migrations/2026-08-02-lm-funder-asset-freshness.sql"),"utf8"),sha=x=>createHash("sha256").update(x).digest("hex"),SIGNING_KEY=Buffer.alloc(32,7);
function fixture(){
 const root="/fixture/application-kit",kit="# Company\nAnicca is autonomous.\n",traction="# Traction\nMRR uses the live ledger.\n",deckSource="MRR {{dashboard:mrr.total_usd}}",spec=JSON.stringify({pages:[{name:"assets",fields:[{name:"deck",type:"file",value_source:"config.deck"},{name:"video",type:"file",value_source:"config.video"}]}],config:{deck:`${root}/deck/deck-en.pdf`,video:`${root}/videos/founder.mp4`}}),dashboard=JSON.stringify({updated_at:"2026-08-02T02:00:00.000Z",mrr:{total_usd:42,sources:{stripe:15,revenuecat_mobile:27}},views:{weekly_total:3540},meta:{fetcher_versions:{stripe:"2026-08-02T01:30:00.000Z",rc:"2026-08-02T01:31:00.000Z",postiz:"2026-08-02T01:32:00.000Z"}}}),files=new Map([[`${root}/KIT.md`,kit],[`${root}/answers/q04_traction.en.md`,traction],[`${root}/deck/deck-en.md`,deckSource],[`${root}/deck/deck-en.pdf`,Buffer.from("%PDF-current-deck")],[`${root}/videos/founder.mp4`,Buffer.from("real-probed-video-bytes")],["/fixture/spec.json",spec],["/fixture/payload.json","{}"]]),mtimes=new Map([[`${root}/KIT.md`,"2026-07-17T09:50:49.000Z"],[`${root}/answers/q04_traction.en.md`,"2026-07-17T09:50:49.000Z"],[`${root}/deck/deck-en.md`,"2026-08-02T01:50:00.000Z"],[`${root}/deck/deck-en.pdf`,"2026-08-02T02:10:00.000Z"],[`${root}/videos/founder.mp4`,"2026-07-30T02:00:00.000Z"]]);
 const input={tenantId:"dais-local",attemptId:randomUUID(),funderId:"spc-f26",evaluatedAt:"2026-08-02T03:00:00.000Z",applicationKitRoot:root,submissionSpecPath:"/fixture/spec.json",payloadPath:"/fixture/payload.json",dashboardUrl:"https://aniccaai.com/dashboard.json",assessment:{company_facts:[{claim_id:"company-autonomy",source_ref:"application-kit://KIT.md",evidence_excerpt:"Anicca is autonomous."}],traction:[{claim_id:"weekly-views",dashboard_pointer:"views.weekly_total",provider_timestamp_pointer:"meta.fetcher_versions.postiz",reported_value:3540,source_ref:"application-kit://answers/q04_traction.en.md",evidence_excerpt:"MRR uses the live ledger."}],mrr:{total_pointer:"mrr.total_usd",reported_value:42,recurring_revenue_pointers:["mrr.sources.stripe","mrr.sources.revenuecat_mobile"],provider_timestamp_pointers:["meta.fetcher_versions.stripe","meta.fetcher_versions.rc"],rationale:"Stripe subscriptions plus RevenueCat mobile subscriptions."},payload_claims:[]},assets:[{kind:"deck",ref:"application-kit://deck/deck-en.pdf",source_ref:"application-kit://deck/deck-en.md"},{kind:"video",ref:"application-kit://videos/founder.mp4"}]};
 const deps={signingKey:SIGNING_KEY,freezeFile:file=>{if(!files.has(file))throw new Error("missing");const v=files.get(file);return {bytes:Buffer.isBuffer(v)?v:Buffer.from(v),mtime:new Date(mtimes.get(file)||"2026-08-02T02:00:00.000Z")};},fetch:async()=>({ok:true,text:async()=>dashboard}),capturedAt:input.evaluatedAt,snapshotKit:()=>({kit_digest:sha("canonical-full-kit")}),probePdf:()=>({pages:9}),probeVideo:()=>({duration_seconds:57.84,video_codec:"h264",audio_codec:"aac",width:720,height:1280})};return {input,deps,files,setDashboard:value=>{deps.fetch=async()=>({ok:true,text:async()=>value});},mtimes};
}
test("trusted collector reads current claims, exact MRR, deck lineage, and probed video",async()=>{const x=fixture(),gate=await collectFunderAssetFreshnessGate(x.input,x.deps);assert.equal(gate.decision,"allow");assert.match(gate.gate_id,/^funder-freshness-gate:[0-9a-f]{64}$/);assert.equal(JSON.stringify(gate).includes("Anicca is autonomous"),false);assert.equal(gate.asset_receipts.length,2);});
test("stale providers, arithmetic drift, fabricated citation, and equal/old deck fail closed",async()=>{const stale={updated_at:"2026-07-01T00:00:00.000Z",mrr:{total_usd:42,sources:{stripe:15,revenuecat_mobile:27}},views:{weekly_total:3540},meta:{fetcher_versions:{stripe:"2026-07-01T00:00:00.000Z",rc:"2026-07-01T00:00:00.000Z",postiz:"2026-07-01T00:00:00.000Z"}}},cases=[x=>x.setDashboard(JSON.stringify(stale)),x=>{x.input.assessment.mrr.reported_value=99;},x=>{x.input.assessment.company_facts[0].evidence_excerpt="invented";},x=>{x.mtimes.set("/fixture/application-kit/deck/deck-en.pdf","2026-08-02T02:00:00.000Z");}];for(const mutate of cases){const x=fixture();mutate(x);const gate=await collectFunderAssetFreshnessGate(x.input,x.deps);assert.equal(gate.decision,"refresh_required");}});
test("collector probes bytes and rejects overlong, oversized, wrong-codec video and bad PDF",async()=>{for(const mutate of [x=>{x.deps.probeVideo=()=>({duration_seconds:60.01,video_codec:"h264",audio_codec:"aac",width:720,height:1280});},x=>{x.deps.probeVideo=()=>({duration_seconds:58,video_codec:"vp9",audio_codec:"aac",width:720,height:1280});},x=>{x.deps.probePdf=()=>({pages:0});}]){const x=fixture();mutate(x);await assert.rejects(()=>collectFunderAssetFreshnessGate(x.input,x.deps),/freshness/i);}});
test("dashboard must be fetched from canonical public ledger",async()=>{const x=fixture();x.input.dashboardUrl="https://evil.example/dashboard.json";await assert.rejects(()=>collectFunderAssetFreshnessGate(x.input,x.deps),/dashboard URL/i);});
test("validator rejects unknown raw fields, forged decisions, and wrong signatures",async()=>{const x=fixture(),gate=await collectFunderAssetFreshnessGate(x.input,x.deps);assert.throws(()=>validateFunderAssetFreshnessGate({...gate,raw_content:"secret"},{signingKey:SIGNING_KEY}),/schema/i);assert.throws(()=>validateFunderAssetFreshnessGate({...gate,decision:"refresh_required"},{signingKey:SIGNING_KEY}),/digest/i);assert.throws(()=>validateFunderAssetFreshnessGate(gate,{signingKey:Buffer.alloc(32,8)}),/digest/i);});
test("gate binds exact spec, payload, every upload, and minimum source expiry",async()=>{const x=fixture(),gate=await collectFunderAssetFreshnessGate(x.input,x.deps);assert.equal(gate.submission_binding.uploads.length,2);assert.equal(gate.expires_at,"2026-08-02T09:00:00.000Z");assert.doesNotThrow(()=>verifyFunderSubmissionBinding(gate,x.input.submissionSpecPath,x.input.payloadPath,x.deps));const original=x.deps.freezeFile;x.deps.freezeFile=file=>file===x.input.payloadPath?{bytes:Buffer.from('{"changed":true}'),mtime:new Date()}:original(file);assert.throws(()=>verifyFunderSubmissionBinding(gate,x.input.submissionSpecPath,x.input.payloadPath,x.deps),/binding/i);});
test("every upload must be the exact attested deck or video, while no-upload forms remain valid",async()=>{const mismatch=fixture();mismatch.files.set("/fixture/application-kit/videos/old.mov",Buffer.from("different-video"));mismatch.files.set("/fixture/spec.json",JSON.stringify({pages:[{name:"assets",fields:[{name:"video",type:"file",value_source:"config.video"}]}],config:{video:"/fixture/application-kit/videos/old.mov"}}));await assert.rejects(()=>collectFunderAssetFreshnessGate(mismatch.input,mismatch.deps),/correspondence/i);const none=fixture();none.files.set("/fixture/spec.json",JSON.stringify({pages:[{name:"about",fields:[{name:"company",type:"text"}]}],config:{}}));const gate=await collectFunderAssetFreshnessGate(none.input,none.deps);assert.equal(gate.submission_binding.uploads.length,0);assert.equal(gate.decision,"allow");});
test("every payload leaf is source-bound and inflated or appended claims are rejected",async()=>{const x=fixture();x.files.set("/fixture/payload.json",JSON.stringify({mrr:1000000,views:3540}));x.input.assessment.payload_claims=[{payload_pointer:"/mrr",kind:"mrr"},{payload_pointer:"/views",kind:"traction",claim_id:"weekly-views"}];await assert.rejects(()=>collectFunderAssetFreshnessGate(x.input,x.deps),/payload MRR/i);x.files.set("/fixture/payload.json",JSON.stringify({mrr:42,views:3540}));const gate=await collectFunderAssetFreshnessGate(x.input,x.deps);assert.equal(gate.payload_claim_receipts.length,2);x.input.assessment.payload_claims.pop();await assert.rejects(()=>collectFunderAssetFreshnessGate(x.input,x.deps),/payload coverage/i);const company=fixture();company.files.set("/fixture/payload.json",JSON.stringify({company:"Anicca is autonomous. MRR is $1M"}));company.input.assessment.payload_claims=[{payload_pointer:"/company",kind:"company_fact",claim_id:"company-autonomy"}];await assert.rejects(()=>collectFunderAssetFreshnessGate(company.input,company.deps),/payload company fact/i);});
test("collector rejects application-kit changes during capture",async()=>{const x=fixture();let calls=0;x.deps.snapshotKit=()=>({kit_digest:calls++?sha("changed-kit"):sha("canonical-full-kit")});await assert.rejects(()=>collectFunderAssetFreshnessGate(x.input,x.deps),/kit changed/i);});
test("ledger is hardened append-only and exact replay only",async()=>{assert.match(SQL,/BEFORE UPDATE OR DELETE/i);assert.match(SQL,/BEFORE TRUNCATE/i);assert.match(SQL,/REVOKE UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER/i);const x=fixture(),gate=await collectFunderAssetFreshnessGate(x.input,x.deps),calls=[];const saved=await appendFunderAssetFreshnessGate(gate,{signingKey:SIGNING_KEY,query:async(sql,params)=>{calls.push({sql,params});return{rows:[{gate_id:params[2]}]};}});assert.equal(saved.inserted,true);assert.match(calls[0].sql,/ON CONFLICT .* DO NOTHING/i);await assert.rejects(()=>appendFunderAssetFreshnessGate(gate,{signingKey:SIGNING_KEY,query:async()=>({rows:[]})}),/collision/i);});
