# Railway NIXPACKS build for life-call. C1 (VCSDD life-manager-cost-connect-reliability) needs the
# edge-tts CLI (free MS-cloud TTS) + ffmpeg (mp3→μ-law 8k) on the PATH so the DEFAULT wake call is a
# one-way clip with NO Gemini Live socket ($0 native-audio). Without these, synthWakeClip throws and
# every call silently escalates to Gemini Live — defeating the whole feature (adversary FIND-001).
# "..." preserves nixpacks' auto-detected Node packages; we only ADD ffmpeg + the edge-tts CLI.
[phases.setup]
nixPkgs = ["...", "ffmpeg", "python313Packages.edge-tts"]
