#!/usr/bin/env bash
# JP pipeline: OpenAI TTS Onyx → 5 fal Kling clips → concat → Whisper segments → ASS per-phrase subs (DP-aligned) → final mp4
# Reads bank_jp.jsonl entry's `phrases` field as source of truth.
set -euo pipefail
ROOT="$HOME/anicca-monk-factory"
set -a; . "$ROOT/.env"; set +a
export PATH="$HOME/.local/bin:$PATH"

TS=$(date +%Y%m%d_%H%M%S)
WORK="$ROOT/renders/jp_${TS}"
mkdir -p "$WORK"
export WORK ROOT TS

# Pull script (kanji form, source of truth for subtitle display)
# Also derive a hiragana-only string to send to TTS (so Onyx reads kanji correctly).
SCRIPT_TEXT=$(python3 - <<'PY'
import json, os
d = json.load(open(os.path.expanduser('~/anicca-monk-factory/state/current_jp.json'), encoding='utf-8'))
print(d.get('full_text',''), end='')
PY
)
TTS_TEXT=$(python3 - <<'PY'
import json, os, pykakasi
d = json.load(open(os.path.expanduser('~/anicca-monk-factory/state/current_jp.json'), encoding='utf-8'))
ft = d.get('full_text','')
kks = pykakasi.kakasi()
print(''.join(r['hira'] for r in kks.convert(ft)), end='')
PY
)
export SCRIPT_TEXT TTS_TEXT

# 1) TTS — ElevenLabs (preferred) or OpenAI fallback. Provider via $JP_TTS_PROVIDER env.
JP_PROVIDER="${JP_TTS_PROVIDER:-elevenlabs}"
if [ "$JP_PROVIDER" = "elevenlabs" ] && [ -n "${ELEVENLABS_API_KEY:-}" ] && [ -n "${JP_TTS_VOICE_ID:-}" ]; then
  echo "🗣 ElevenLabs TTS (${JP_TTS_VOICE_NAME:-bill})..." >&2
  # JP-v3 (Dais 2026-05-23): send NATURAL kanji+kana (SCRIPT_TEXT), NOT hiragana.
  # eleven_v3 has a real JP tokenizer — feeding all-hiragana (old TTS_TEXT) broke
  # word boundaries/pitch and sounded awkward. Kanji input + v3 = natural narration.
  TTS_PAYLOAD=$(python3 - <<'PY'
import json, os
print(json.dumps({
  'text': os.environ['SCRIPT_TEXT'],
  'model_id': os.environ.get('JP_TTS_MODEL', 'eleven_v3'),
  'voice_settings': {'stability': 0.5, 'similarity_boost': 0.75, 'style': 0.15, 'use_speaker_boost': True}
}))
PY
)
  curl -sS -X POST "https://api.elevenlabs.io/v1/text-to-speech/${JP_TTS_VOICE_ID}" \
    -H "xi-api-key: $ELEVENLABS_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$TTS_PAYLOAD" \
    --output "$WORK/narration.mp3"
else
  echo "🗣 OpenAI Onyx TTS (fallback)..." >&2
  TTS_PAYLOAD=$(python3 - <<'PY'
import json, os
print(json.dumps({
  'model': 'tts-1-hd',
  'input': os.environ['TTS_TEXT'],
  'voice': 'onyx',
  'speed': 1.0,
  'response_format': 'mp3'
}))
PY
)
  curl -sS -X POST "https://api.openai.com/v1/audio/speech" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$TTS_PAYLOAD" \
    --output "$WORK/narration.mp3"
fi

AUDIO_DUR=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$WORK/narration.mp3")
echo "  audio: ${AUDIO_DUR}s" >&2

# 2) Use cached Kling i2v library — pre-generated by preload-kling-library.sh
#    (one-time bootstrap $2.73, then $0 per render — Locked Asset Rule, CA1 2026-05-08)
echo "🎞 use cached Kling library (audio-independent motion, \$0/render)..." >&2
for i in 02 03 04 05 06 07 08 09 10 12 13; do
  CACHED_KLING="$ROOT/state/jp_kling_clip_$i.mp4"
  if [ ! -f "$CACHED_KLING" ] || [ ! -s "$CACHED_KLING" ]; then
    echo "❌ missing $CACHED_KLING — run preload-kling-library.sh ONCE first" >&2
    exit 4
  fi
  cp "$CACHED_KLING" "$WORK/clip_$i.mp4"
  echo "  clip $i ✅ (cached, $(du -h "$CACHED_KLING" | cut -f1))" >&2
done

# 3) Concat — 11 × 5s = 55s of unique watercolor scenes; loop to fill audio if needed (30 fps out)
# (scenes 01 + 11 removed 2026-05-08 per Dais visual review — only 11 scenes rotate now)
echo "🔗 concat 11 scenes (loop to audio)..." >&2
for i in 02 03 04 05 06 07 08 09 10 12 13; do echo "file 'clip_$i.mp4'"; done > "$WORK/concat.txt"
VIDEO_DUR=$(python3 -c "print(${AUDIO_DUR} + 0.5)")
ffmpeg -y -stream_loop -1 -f concat -safe 0 -i "$WORK/concat.txt" -c:v libx264 -preset medium -crf 22 -an -r 30 -t "$VIDEO_DUR" "$WORK/concat.mp4" 2>/dev/null

# 4) Whisper word-level for accurate phrase alignment
python3 - <<'PY'
import os, whisper, json
m = whisper.load_model('base')
r = m.transcribe(os.path.join(os.environ['WORK'],'narration.mp3'), word_timestamps=True, language='ja', fp16=False)
words = []
for seg in r['segments']:
    for w in seg.get('words', []):
        words.append({'word': w['word'].strip(), 'start': float(w['start']), 'end': float(w['end'])})
json.dump(words, open(os.path.join(os.environ['WORK'],'words.json'),'w'), ensure_ascii=False, indent=2)
PY

# 5) Build ASS — bank phrases are TRUTH, Whisper words give timestamps via DP alignment
python3 - <<'PY'
import os, json, re
WORK = os.environ['WORK']
ROOT = os.environ['ROOT']
words = json.load(open(os.path.join(WORK, 'words.json')))
d = json.load(open(os.path.join(ROOT, 'state', 'current_jp.json'), encoding='utf-8'))
phrases = d.get('phrases') or [d.get('full_text','')]
audio_end = max((w['end'] for w in words), default=0)

# Use sequential character-count proportional alignment to map phrases to time
# Each phrase gets duration proportional to its length
total_chars = sum(max(len(p.replace('「','').replace('」','').replace('…','').replace('。','').replace('、','')), 1) for p in phrases)
# Build cumulative phrase positions in source text (without spaces)
src_concat = ''.join(phrases)
# Stream Whisper words and assign each phrase its time based on cumulative chars
char_per_sec = total_chars / audio_end if audio_end > 0 else 1
mapped = []
cumulative_chars = 0
for p in phrases:
    p_clean_len = len(p.replace('「','').replace('」','').replace('…','').replace('。','').replace('、','').strip())
    p_len = max(p_clean_len, 1)
    start_t = cumulative_chars / char_per_sec if char_per_sec > 0 else 0
    cumulative_chars += p_len
    end_t = cumulative_chars / char_per_sec if char_per_sec > 0 else audio_end
    mapped.append((p, start_t, end_t))

# STRICT non-overlap: each phrase ends EXACTLY where the next begins
# → only 1 phrase visible at any moment, max 2 wrap-lines, never 4
def snap(t, words):
    if not words: return t
    return min(words, key=lambda w: abs(w['start']-t))['start']

# Step 1: snap phrase START times to whisper word boundaries
starts = []
for i,(p,s,e) in enumerate(mapped):
    rs = snap(s, words)
    if i > 0:
        rs = max(rs, starts[-1] + 0.4)
    starts.append(rs)

# Step 2: phrase[i].end = phrase[i+1].start (no overlap, hard cut)
refined = []
for i, (p, _s, _e) in enumerate(mapped):
    rs = starts[i]
    re_ = starts[i+1] if i+1 < len(starts) else audio_end
    if re_ <= rs:
        re_ = rs + 0.4
    refined.append((p, rs, re_))

def t(s):
    h = int(s//3600); m = int((s%3600)//60); sec = s%60
    return f'{h:01d}:{m:02d}:{sec:05.2f}'

ass = '''[Script Info]
ScriptType: v4.00+
PlayResX: 720
PlayResY: 1280
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: JP,Hiragino Mincho ProN,42,&H00FFFFFF,&H00FFFFFF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2,0,2,40,40,580,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
'''

# JP-7 (2026-05-04): KANJI display (isshin pattern). Subtitle shows the original kanji surface,
# NOT hiragana. TTS gets hiragana separately at the top of this script (TTS_TEXT). janome
# gives word boundaries on the kanji form (most accurate); we glue clinging particles back.
from janome.tokenizer import Tokenizer
_tok = Tokenizer()

# Particles/punctuation that visually cling to the previous word — never start a line.
GLUE_BACK_PARTICLES = set(['て','た','だ','に','で','を','が','は','と','の','も','ね','よ','さ','し','か',
                            '、','。','？','！','…','」','』'])

def tokenize_kanji_words(phrase):
    """Tokenize kanji phrase; return KANJI surface words. Glue trailing single-particle/punct
       tokens to the preceding word so 立ち止まっ\\Nて does not happen."""
    raw = [t.surface for t in _tok.tokenize(phrase)]
    out = []
    for w in raw:
        if w in GLUE_BACK_PARTICLES and out:
            out[-1] = out[-1] + w
        else:
            out.append(w)
    return out

def pack_scenes(hira_words, max_per_line=18):
    """Greedy line-pack: scene = up to 3 lines, each ≤ max_per_line.
       Default behavior is 2 lines/scene, BUT if the last scene would otherwise be a tiny
       orphan (≤8 chars like 'ませんか。'), absorb it as a 3rd line of the previous scene."""
    scenes = []
    l1, l2, l3, n1, n2, n3 = [], [], [], 0, 0, 0
    for w in hira_words:
        ln = len(w)
        if not l2 and n1 + ln <= max_per_line:
            l1.append(w); n1 += ln
        elif not l3 and n2 + ln <= max_per_line:
            l2.append(w); n2 += ln
        else:
            scenes.append((l1, l2, []))
            l1, l2, l3, n1, n2, n3 = [w], [], [], ln, 0, 0
    if l1 or l2:
        scenes.append((l1, l2, []))
    # Orphan absorption: if last scene's total chars ≤ 8, append as line 3 of prev
    if len(scenes) >= 2:
        last_l1, last_l2, _ = scenes[-1]
        last_total = sum(len(w) for w in last_l1) + sum(len(w) for w in last_l2)
        if last_total <= 8 and not last_l2:
            prev_l1, prev_l2, prev_l3 = scenes[-2]
            absorbed_l3 = last_l1
            if sum(len(w) for w in absorbed_l3) <= max_per_line:
                scenes[-2] = (prev_l1, prev_l2, absorbed_l3)
                scenes.pop()
    return scenes

def fmt_scene(l1_words, l2_words, l3_words=None):
    s1 = ''.join(l1_words); s2 = ''.join(l2_words); s3 = ''.join(l3_words or [])
    out = s1
    if s2:
        out += '\\N' + s2
    if s3:
        out += '\\N' + s3
    return out

for txt, s, e in refined:
    txt = txt.replace('\n', ' ').strip()
    kanji_words = tokenize_kanji_words(txt)
    scenes = pack_scenes(kanji_words, max_per_line=18)
    if not scenes:
        continue
    total = sum(sum(len(w) for w in (l1+l2+l3)) for (l1,l2,l3) in scenes) or 1
    cum = 0
    for (l1, l2, l3) in scenes:
        sub_s = s + (e - s) * (cum / total)
        cum += sum(len(w) for w in (l1+l2+l3))
        sub_e = s + (e - s) * (cum / total)
        if sub_e <= sub_s:
            sub_e = sub_s + 0.4
        ass += f'Dialogue: 0,{t(sub_s)},{t(sub_e)},JP,,0,0,580,,{fmt_scene(l1,l2,l3)}\n'
open(os.path.join(WORK, 'subs.ass'), 'w', encoding='utf-8').write(ass)
PY

# 6) Final assemble — burn subs + mix BGM at -18dB (narration on top)
BGM="$ROOT/assets/bgm/charlie_sky_mindfulness.mp3"
FINAL="$ROOT/renders/jp_${TS}_final.mp4"
if [ -f "$BGM" ]; then
  ffmpeg -y -i "$WORK/concat.mp4" -i "$WORK/narration.mp3" -stream_loop -1 -i "$BGM" \
    -filter_complex "[2:a]volume=0.05[bgm];[1:a][bgm]amix=inputs=2:duration=first:dropout_transition=0[a];[0:v]tpad=stop_mode=clone:stop_duration=4,subtitles=$WORK/subs.ass[v]" \
    -map "[v]" -map "[a]" -c:v libx264 -preset medium -crf 22 -c:a aac -b:a 192k -shortest \
    "$FINAL" 2>/dev/null
else
  ffmpeg -y -i "$WORK/concat.mp4" -i "$WORK/narration.mp3" \
    -filter_complex "[0:v]tpad=stop_mode=clone:stop_duration=4,subtitles=$WORK/subs.ass[v]" \
    -map "[v]" -map 1:a -c:v libx264 -preset medium -crf 22 -c:a aac -b:a 192k -shortest \
    "$FINAL" 2>/dev/null
fi

echo "$FINAL"
