#!/usr/bin/env bash
# Stage 4: SPAWN — copy template, replace placeholders, drop into ~/.openclaw/skills/<slug>-factory/
set -euo pipefail
RUN_DIR="${1:?run_dir required}"
NICHE_SLUG="${2:?niche_slug required}"
LANG_ARG="${3:?lang required}"

SKILL_DIR="$HOME/.openclaw/skills/copy-viral-format-factory"
TEMPLATE_DIR="$SKILL_DIR/scripts/templates/factory-skeleton"
TARGET_DIR="$HOME/.openclaw/skills/${NICHE_SLUG}-factory"

ROOT="$HOME/anicca-monk-factory"
set -a; . "$ROOT/.env"; set +a

echo ""
echo "─── Stage 4: SPAWN ───"

if [ -d "$TARGET_DIR" ]; then
  N=2
  while [ -d "${TARGET_DIR}-v${N}" ]; do N=$((N+1)); done
  TARGET_DIR="${TARGET_DIR}-v${N}"
fi
echo "  target: $TARGET_DIR"
mkdir -p "$TARGET_DIR/scripts"

# Read clone_spec.json for template variables
CLONE_SPEC="$RUN_DIR/clone_spec.json"
if [ ! -f "$CLONE_SPEC" ]; then
  echo "  ❌ no clone_spec.json"; exit 2
fi

# Honor agent's skip signal (source isn't actually AI viral)
SKIP=$(python3 -c "import json; d=json.load(open('$CLONE_SPEC')); print('1' if d.get('skip') else '0')")
if [ "$SKIP" = "1" ]; then
  REASON=$(python3 -c "import json; d=json.load(open('$CLONE_SPEC')); print(d.get('reason','no reason'))")
  echo ""
  echo "  ⏭ SKIP — agent rejected source"
  echo "  reason: $REASON"
  echo ""
  echo "  No factory spawned. Update seed_ai_handles.txt with verified-AI-viral handles and re-run."
  rmdir "$TARGET_DIR/scripts" "$TARGET_DIR" 2>/dev/null || true
  exit 0
fi

FORMAT_TYPE=$(python3 -c "import json; print(json.load(open('$CLONE_SPEC')).get('format_type','talking-head'))")
PRODUCTION_STACK=$(python3 -c "import json; print(json.load(open('$CLONE_SPEC')).get('production_stack','heygen'))")
NICHE_SLUG_UC=$(echo "$NICHE_SLUG" | tr 'a-z-' 'A-Z_')

# Decide which seed factory to copy as base — pick by archetype
case "$FORMAT_TYPE" in
  talking-head)             SEED="yangmun-monk-factory" ;;
  image-to-video)           SEED="watercolor-monk-factory" ;;
  animated-short)           SEED="watercolor-monk-factory" ;;
  slideshow)                SEED="4.7-slideshow-factory" ;;
  podcast-clip|podcast-2person) SEED="yangmun-monk-factory" ;;  # talking-head base + post-process concat
  faceless-long)            SEED="yangmun-monk-factory" ;;       # body talking-head + Pexels b-roll TODO
  cinematic-narrative)      SEED="watercolor-monk-factory" ;;    # extends with Veo3 hook
  text-on-loop)             SEED="4.7-slideshow-factory" ;;
  ugc)                      SEED="yangmun-monk-factory" ;;
  *)                        SEED="yangmun-monk-factory" ;;
esac
echo "  seed factory: $SEED → $FORMAT_TYPE / $PRODUCTION_STACK"

# Copy seed factory's scripts as a starting point
SEED_DIR="$HOME/.openclaw/skills/$SEED"
if [ -d "$SEED_DIR/scripts" ]; then
  cp -r "$SEED_DIR/scripts/"* "$TARGET_DIR/scripts/" 2>/dev/null || true
fi

# Patch spawned scripts to point at SELF (not the seed) — true independence per Dais v4
for f in "$TARGET_DIR/scripts/"*.sh; do
  [ -f "$f" ] || continue
  sed -i '' \
    -e "s|\\\$HOME/.openclaw/skills/yangmun-monk-factory|\\\$HOME/.openclaw/skills/${NICHE_SLUG}-factory|g" \
    -e "s|\\\$HOME/.openclaw/skills/watercolor-monk-factory|\\\$HOME/.openclaw/skills/${NICHE_SLUG}-factory|g" \
    "$f" 2>/dev/null || true
done

# Patch rotate_script to use SPAWNED bank (per-niche)
ROTATE="$TARGET_DIR/scripts/rotate_script.sh"
if [ -f "$ROTATE" ]; then
  sed -i '' "s|bank_\${LANG}.jsonl|bank_${NICHE_SLUG}_\${LANG}.jsonl|g; s|bank_\$LANG.jsonl|bank_${NICHE_SLUG}_\$LANG.jsonl|g" "$ROTATE"
fi

# Write the new SKILL.md
cat > "$TARGET_DIR/SKILL.md" <<EOF
---
name: ${NICHE_SLUG}-factory
description: "Auto-spawned factory for niche '${NICHE_SLUG}' (lang=${LANG_ARG}, format=${FORMAT_TYPE}). Generated by virality-copy-factory."
metadata:
  tags: ${NICHE_SLUG}, auto-spawned, ${FORMAT_TYPE}, ${LANG_ARG}
  spawned_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
  spawned_from: $(basename $RUN_DIR)
  format_type: ${FORMAT_TYPE}
  production_stack: ${PRODUCTION_STACK}
  status: NEEDS_AVATAR_PROVISION
  requires:
    bins: [ffmpeg, ffprobe, curl, python3]
    env: [HEYGEN_${NICHE_SLUG_UC}_AVATAR_LOOK_ID, HEYGEN_${NICHE_SLUG_UC}_VOICE_ID, OPENAI_API_KEY, POSTIZ_API_KEY]
---

# ${NICHE_SLUG}-factory — auto-spawned

This factory was generated by virality-copy-factory based on viral TikTok analysis.

**Status: NEEDS AVATAR PROVISION**

## Manual setup steps (before this skill can run)

1. Read the clone spec at the run directory of virality-copy-factory.
2. Provision the avatar:
   - For HeyGen: create a Photo Avatar matching the spec, copy the avatar_id and voice_id.
   - For fal flux: generate 5 reference images, save to \`~/anicca-monk-factory/characters/${NICHE_SLUG}/refs/\`.
3. Add to \`~/anicca-monk-factory/.env\`:
   - HEYGEN_${NICHE_SLUG_UC}_AVATAR_LOOK_ID=<id>
   - HEYGEN_${NICHE_SLUG_UC}_VOICE_ID=<id>
4. Bless personas.json with the new persona slug + bank path.
5. Schedule the cron (see cron.template.txt in this directory).

## How to run (after provisioning)

\`\`\`
bash ~/.openclaw/skills/${NICHE_SLUG}-factory/scripts/run-detached.sh ${LANG_ARG} <slot>
\`\`\`

The pipeline mirrors anicca-monk-factory but loads ${NICHE_SLUG}-specific assets.

EOF

# Write CHARACTER_PROMPTS.md from clone_spec
python3 - <<'PY' "$CLONE_SPEC" "$TARGET_DIR/CHARACTER_PROMPTS.md" "$NICHE_SLUG" "$FORMAT_TYPE"
import json, sys
spec_path, out_path, slug, archetype = sys.argv[1:5]
spec = json.load(open(spec_path))
md = [
    f'# Character Prompts — {slug}',
    f'_From clone_spec.json_', '',
    f'archetype: {archetype}',  # used by copy-viral-format-factory dedupe to skip already-covered
    '',
    f'## Format: {spec.get("format_type")}',
    f'## Stack: {spec.get("production_stack")}',
    '',
    '## Avatar Prompt (paste into HeyGen Photo Avatar or fal flux)',
    '```',
    spec.get('avatar', {}).get('heygen_prompt', ''),
    '```',
    '',
    '## Voice',
    f'- OpenAI TTS suggestion: `{spec.get("voice", {}).get("openai_tts_voice_suggestion", "")}`',
    f'- Tone: {spec.get("voice", {}).get("tone", "")}',
    f'- Pace: {spec.get("voice", {}).get("pace", "")}',
    '',
    '## Visual style',
    f'- BGM: {spec.get("visual_style", {}).get("bgm_type", "")}',
    f'- Color: {spec.get("visual_style", {}).get("color_palette", [])}',
    '',
    '## Hook pattern',
    f'> {spec.get("hook_pattern", "")}',
    '',
    '## Structure',
    f'> {spec.get("structure", "")}',
]
open(out_path, 'w').write('\n'.join(md))
PY

# Copy the new bank into the right place
mkdir -p "$ROOT/scripts"
BANK_PATH="$ROOT/scripts/bank_${NICHE_SLUG}_${LANG_ARG}.jsonl"
if [ -f "$RUN_DIR/new_bank.jsonl" ]; then
  cp "$RUN_DIR/new_bank.jsonl" "$BANK_PATH"
  echo "  ✅ bank → $BANK_PATH"
fi

# Write a cron template (Dais will run after provisioning)
cat > "$TARGET_DIR/cron.template.txt" <<EOF
# After avatar/voice provisioned + persona warmed up + tested manually,
# run these commands to schedule daily posts.

# Morning slot (~09:13 JST)
openclaw cron add \\
  --name ${NICHE_SLUG}-${LANG_ARG}-morning \\
  --cron "13 9 * * *" \\
  --tz "Asia/Tokyo" \\
  --session isolated \\
  --agent anicca \\
  --model "openai-codex/gpt-5.4-mini" \\
  --timeout-seconds 300 \\
  --no-deliver \\
  --message "Read ~/.openclaw/skills/${NICHE_SLUG}-factory/SKILL.md, then run: bash ~/.openclaw/skills/${NICHE_SLUG}-factory/scripts/run-detached.sh ${LANG_ARG} morning. Returns immediately. Do NOT report to Slack yourself."

# Evening slot (~19:27 JST)
openclaw cron add \\
  --name ${NICHE_SLUG}-${LANG_ARG}-evening \\
  --cron "27 19 * * *" \\
  --tz "Asia/Tokyo" \\
  --session isolated \\
  --agent anicca \\
  --model "openai-codex/gpt-5.4-mini" \\
  --timeout-seconds 300 \\
  --no-deliver \\
  --message "Read ~/.openclaw/skills/${NICHE_SLUG}-factory/SKILL.md, then run: bash ~/.openclaw/skills/${NICHE_SLUG}-factory/scripts/run-detached.sh ${LANG_ARG} evening. Returns immediately. Do NOT report to Slack yourself."
EOF

echo "  ✅ cron.template.txt → $TARGET_DIR/cron.template.txt"

# Append source dedupe registries
ALREADY_VID="$ROOT/state/already_spawned_source_ids.txt"
ALREADY_AUTH="$ROOT/state/already_spawned_authors.txt"
SOURCE_ID=$(python3 -c "import json; d=json.load(open('$RUN_DIR/picked.json')); print(d.get('id',''))")
SOURCE_AUTHOR=$(python3 -c "import json; d=json.load(open('$RUN_DIR/picked.json')); print(d.get('author_handle',''))")
[ -n "$SOURCE_ID" ] && echo "$SOURCE_ID" >> "$ALREADY_VID"
[ -n "$SOURCE_AUTHOR" ] && echo "$SOURCE_AUTHOR" >> "$ALREADY_AUTH"

# Save base avatar frame (from Stage 2) into spawned skill character dir
mkdir -p "$ROOT/characters/${NICHE_SLUG}"
BASE_FRAME=$(ls "$RUN_DIR"/*_base.jpg 2>/dev/null | head -1)
if [ -n "$BASE_FRAME" ]; then
  cp "$BASE_FRAME" "$ROOT/characters/${NICHE_SLUG}/base_avatar.jpg"
  echo "  ✅ base avatar frame → $ROOT/characters/${NICHE_SLUG}/base_avatar.jpg"
fi

# HeyGen Photo Avatar provisioning — REQUIRED (no yangmun fallback per Dais 2026-05-06)
NICHE_SLUG_UC=$(echo "$NICHE_SLUG" | tr 'a-z-' 'A-Z_')
AVATAR_ID=""
AVATAR_LOOK_ID=""
if [ -n "$BASE_FRAME" ] && command -v heygen >/dev/null 2>&1; then
  echo "  🎨 HeyGen Photo Avatar from base frame..."
  # Step 1: upload base frame as asset
  ASSET_RESP=$(heygen asset create --file "$BASE_FRAME" 2>&1 || true)
  ASSET_ID=$(echo "$ASSET_RESP" | python3 -c "
import json, sys
try: print(json.load(sys.stdin).get('data',{}).get('asset_id',''))
except: print('')" 2>/dev/null || echo '')
  if [ -z "$ASSET_ID" ]; then
    echo "  ⚠ asset upload failed: $(echo "$ASSET_RESP" | head -c 250)"
  else
    echo "    asset_id: $ASSET_ID"
    # Step 2: create photo avatar
    AVATAR_PAYLOAD=$(ASSET_ID="$ASSET_ID" NICHE_SLUG="$NICHE_SLUG" python3 -c "
import json, os
print(json.dumps({
    'type': 'photo',
    'name': os.environ['NICHE_SLUG'] + '-spawned',
    'file': {'type': 'asset_id', 'asset_id': os.environ['ASSET_ID']}
}))")
    AVATAR_RESP=$(heygen avatar create -d "$AVATAR_PAYLOAD" 2>&1 || true)
    AVATAR_ID=$(echo "$AVATAR_RESP" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin).get('data', {})
    # photo avatar response shape: data.avatar_item.id + data.avatar_group.id
    item = d.get('avatar_item') or {}
    print(item.get('id') or d.get('avatar_id') or d.get('id') or '')
except: print('')" 2>/dev/null || echo '')
    AVATAR_LOOK_ID=$(echo "$AVATAR_RESP" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin).get('data', {})
    item = d.get('avatar_item') or {}
    # avatar_item.id IS the look id for photo avatars
    print(item.get('id') or '')
except: print('')" 2>/dev/null || echo '')
    if [ -n "$AVATAR_LOOK_ID" ]; then
      echo "  ✅ HeyGen avatar created: avatar_id=$AVATAR_ID look_id=$AVATAR_LOOK_ID"
    else
      echo "  ❌ HeyGen avatar create failed: $(echo "$AVATAR_RESP" | head -c 300)"
    fi
  fi
fi

# ElevenLabs voice design — REQUIRED (no yangmun fallback)
VOICE_ID=""
if [ -f "$RUN_DIR/clone_spec.json" ] && [ -n "${ELEVENLABS_API_KEY:-}" ]; then
  echo "  🎙 ElevenLabs voice design from clone spec..."
  VOICE_DESC=$(python3 -c "
import json
d = json.load(open('$RUN_DIR/clone_spec.json'))
desc = d.get('voice', {}).get('elevenlabs_voice_description', '')
print(desc[:1500] if desc else 'A clear narrator voice matching the viral source video.')")
  # ElevenLabs requires text >= 100 chars (verified 2026-05-06)
  PREVIEW_PAYLOAD=$(VOICE_DESC="$VOICE_DESC" python3 -c "
import json, os
sample = ('In every breath, the wisdom of impermanence quietly speaks. Listen, my friend. '
          'There is no rush. The heart is allowed to be still. What hurts you today may '
          'already be changing shape, becoming softer like morning light over still water. '
          'You are not behind. You are exactly here, where the breath is asking to be felt.')
print(json.dumps({
    'voice_description': os.environ['VOICE_DESC'],
    'text': sample,
}))")
  PREVIEW_RESP=$(curl -sS -X POST "https://api.elevenlabs.io/v1/text-to-voice/create-previews" \
    -H "xi-api-key: $ELEVENLABS_API_KEY" -H "Content-Type: application/json" \
    -d "$PREVIEW_PAYLOAD" 2>&1 || true)
  PREVIEW_VOICE_ID=$(echo "$PREVIEW_RESP" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
    previews = d.get('previews', [])
    print(previews[0].get('generated_voice_id', '') if previews else '')
except: print('')" 2>/dev/null || echo '')
  if [ -n "$PREVIEW_VOICE_ID" ]; then
    echo "  ✓ preview generated: $PREVIEW_VOICE_ID  (persisting to library...)"
    # Persist preview → permanent voice_id (required for TTS, not directly usable from preview)
    PERSIST_PAYLOAD=$(VID="$PREVIEW_VOICE_ID" NICHE="$NICHE_SLUG" python3 -c "
import json, os
print(json.dumps({
    'voice_name': os.environ['NICHE'] + '-spawned',
    'voice_description': 'Auto-spawned voice for ' + os.environ['NICHE'] + ' factory by copy-viral-format-factory',
    'generated_voice_id': os.environ['VID']
}))")
    PERSIST_RESP=$(curl -sS -X POST "https://api.elevenlabs.io/v1/text-to-voice/create-voice-from-preview" \
      -H "xi-api-key: $ELEVENLABS_API_KEY" -H "Content-Type: application/json" \
      -d "$PERSIST_PAYLOAD" 2>&1 || true)
    PERMANENT_VOICE_ID=$(echo "$PERSIST_RESP" | python3 -c "
import json, sys
try: print(json.load(sys.stdin).get('voice_id', ''))
except: print('')" 2>/dev/null || echo '')
    if [ -n "$PERMANENT_VOICE_ID" ]; then
      VOICE_ID="$PERMANENT_VOICE_ID"
      echo "  ✅ ElevenLabs voice persisted: $VOICE_ID"
    else
      echo "  ❌ persist failed (likely 3/3 voice slot limit). Resp: $(echo "$PERSIST_RESP" | head -c 250)"
      echo "     → spawn marked invalid; Dais must free 1 ElevenLabs voice slot or upgrade"
    fi
  else
    echo "  ❌ ElevenLabs preview create failed: $(echo "$PREVIEW_RESP" | head -c 200)"
  fi
fi

# Strict gating: spawn fails loudly if either avatar or voice is missing — NO yangmun fallback.
SPAWN_VALID=1
if [ -z "$AVATAR_LOOK_ID" ]; then
  echo "  ❌ avatar_look_id missing — spawn will be marked PROVISION_PENDING (Dais must fix HeyGen)"
  SPAWN_VALID=0
fi
if [ -z "$VOICE_ID" ]; then
  echo "  ❌ voice_id missing — spawn will be marked PROVISION_PENDING (Dais must fix ElevenLabs)"
  SPAWN_VALID=0
fi

# Spawned skill .env (each new factory has its OWN avatar+voice — never shared with yangmun)
cat > "$TARGET_DIR/.env" <<ENVEOF
# Spawned ${NICHE_SLUG}-factory env (auto-generated $(date -u +%Y-%m-%dT%H:%M:%SZ))
# Source: @${SOURCE_AUTHOR}, video ${SOURCE_ID}
# This skill MUST use its OWN avatar+voice. NEVER fall back to yangmun-monk-factory.

HEYGEN_${NICHE_SLUG_UC}_AVATAR_LOOK_ID=${AVATAR_LOOK_ID:-__PROVISION_PENDING__}
HEYGEN_${NICHE_SLUG_UC}_AVATAR_ID=${AVATAR_ID:-__PROVISION_PENDING__}
${NICHE_SLUG_UC}_VOICE_ID=${VOICE_ID:-__PROVISION_PENDING__}
${NICHE_SLUG_UC}_SPAWN_VALID=${SPAWN_VALID}
ENVEOF
echo "  ✅ .env → $TARGET_DIR/.env (spawn_valid=${SPAWN_VALID})"

# Write SOURCE.json — canonical provenance for future Stage 1 dedup.
# Future runs of 01_discover.sh read this and exclude $SOURCE_AUTHOR from candidates.
python3 - <<PY
import json, datetime
src = json.load(open("$RUN_DIR/picked.json"))
spec = json.load(open("$CLONE_SPEC"))
out = {
  "source_handle": src.get("author_handle",""),
  "source_id": src.get("id",""),
  "source_url": src.get("web_video_url",""),
  "source_play_count": src.get("play_count",0),
  "source_duration_sec": src.get("duration_sec",0),
  "format_type": spec.get("format_type",""),
  "production_stack": spec.get("production_stack",""),
  "spawned_at": datetime.datetime.utcnow().isoformat()+"Z",
  "spawned_by": "copy-viral-format-factory",
  "spawned_run_dir": "$RUN_DIR",
}
json.dump(out, open("$TARGET_DIR/SOURCE.json","w"), indent=2, ensure_ascii=False)
print(f"  ✅ SOURCE.json → @{out['source_handle']} / {out['format_type']}")
PY

# Patch spawned generate.sh / generate_en.sh to use ITS OWN avatar+voice env
# AND source the spawned skill's own .env so env vars resolve.
for gen in "$TARGET_DIR/scripts/generate_en.sh" "$TARGET_DIR/scripts/generate.sh"; do
  [ -f "$gen" ] || continue
  # Replace specific references — BSD sed doesn't support \b, use exact tokens
  sed -i '' \
    -e "s|HEYGEN_EN_AVATAR_LOOK_ID|HEYGEN_${NICHE_SLUG_UC}_AVATAR_LOOK_ID|g" \
    -e "s|os.environ\\['EN_VOICE_ID'\\]|os.environ['${NICHE_SLUG_UC}_VOICE_ID']|g" \
    -e "s|\\\${EN_VOICE_ID}|\\\${${NICHE_SLUG_UC}_VOICE_ID}|g" \
    -e "s|\\\$EN_VOICE_ID|\\\$${NICHE_SLUG_UC}_VOICE_ID|g" \
    "$gen" 2>/dev/null || true
  # Inject spawned .env source after the brand .env source
  python3 - "$gen" "$TARGET_DIR/.env" <<'PY'
import sys, re
gen, env_path = sys.argv[1:3]
src = open(gen).read()
inj = f'\n# Load spawned skill .env (per-spawn avatar/voice overrides)\n[ -f "{env_path}" ] && {{ set -a; . "{env_path}"; set +a; }}\n'
new = re.sub(r'(set -a; \. "\$ROOT/\.env"; set \+a\n)', r'\1' + inj, src, count=1)
if new != src:
    open(gen, 'w').write(new)
PY
done

# Copy ORIGINAL viral videos + GENERATED test render to Desktop (side-by-side)
DESKTOP_DIR="$HOME/Desktop/anicca-monk-demo/cvff_spawned/${NICHE_SLUG}"
mkdir -p "$DESKTOP_DIR/originals" "$DESKTOP_DIR/clones"
# Original viral videos (top 3-5 from this account)
for mp4 in "$RUN_DIR"/source_*.mp4; do
  [ -f "$mp4" ] || continue
  cp "$mp4" "$DESKTOP_DIR/originals/$(basename "$mp4")"
done
# Spec + bank artifacts
cp "$RUN_DIR/picked.json" "$DESKTOP_DIR/_picked_source.json" 2>/dev/null || true
cp "$RUN_DIR/clone_spec.json" "$DESKTOP_DIR/_clone_spec.json" 2>/dev/null || true
cp "$RUN_DIR/reverse_spec.md" "$DESKTOP_DIR/_clone_spec.md" 2>/dev/null || true
cp "$RUN_DIR/new_bank.jsonl" "$DESKTOP_DIR/_bank_30_entries.jsonl" 2>/dev/null || true
echo "  📂 Desktop originals: $DESKTOP_DIR/originals/"
echo "  📂 Desktop clones (filled by Stage 5): $DESKTOP_DIR/clones/"

echo "  ✅ spawn complete: $TARGET_DIR"
