#!/usr/bin/env bash
# 04-render.sh — Remotion render (9:16 EN + 16:9 EN + 9:16 JA)
set -euo pipefail

SKILL_DIR="${SKILL_DIR:-$HOME/.openclaw/skills/sao-content-factory}"
source "$SKILL_DIR/lib/render.sh"

[ -n "${VERSION_DIR:-}" ] || { echo "VERSION_DIR not set" >&2; exit 2; }
ENTITY_LOCAL="$VERSION_DIR/docs/entity.json"

# Install entity assets into Remotion public/
install_assets "$VERSION_DIR"

# Update Remotion data file with this entity's scenes
DATA_TS="$REMOTION_DIR/src/data/andon.ts"
{
  echo "// Auto-generated by sao-content-factory phase 04"
  echo "import type { Scene } from './types';"
  echo ""
  echo "export const andonScenes: Scene[] = $(jq '.scenes' "$ENTITY_LOCAL") as Scene[];"
} > "$DATA_TS"

# Render 3 outputs
render_reel "SaoReel9x16" "$VERSION_DIR/output/reel_9x16_en.mp4"
render_reel "SaoReel16x9" "$VERSION_DIR/output/reel_16x9_en.mp4"
render_reel "SaoReel9x16JA" "$VERSION_DIR/output/reel_9x16_ja.mp4"

# Encode small version for {{profile.lateness.stakeholders.channel}}
encode_small "$VERSION_DIR/output/reel_9x16_en.mp4" "$VERSION_DIR/output/reel_9x16_en_small.mp4"

echo "phase 04 ok (3 reels rendered)"
